// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class FileManager
{
    public int Id { get; set; }

    public string Url { get; set; }

    public string Caption { get; set; }

    public int? Priority { get; set; }

    public int? ContentId { get; set; }
}