// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class City
{
    public int CityId { get; set; }

    public string CityName { get; set; }

    public int? CountryId { get; set; }

    public virtual ICollection<LaneAddress> LaneAddresses { get; set; } = new List<LaneAddress>();

    public virtual ICollection<StateProvince> StateProvinces { get; set; } = new List<StateProvince>();
}