// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Country
{
    public int CountryId { get; set; }

    public string CountryName { get; set; }

    public string Isocode { get; set; }

    public string CountryDialCode { get; set; }

    public string CurrencyFormat { get; set; }

    public string TopLevelDomain { get; set; }

    public virtual ICollection<StateProvince> StateProvinces { get; set; } = new List<StateProvince>();
}