// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string EmployeeCode { get; set; }

    public int? DepartmentId { get; set; }

    public int? DesignationId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public bool? IsActive { get; set; }

    public int? PersonId { get; set; }

    public bool? IsSalePerson { get; set; }

    public virtual EmployeeDepartment Department { get; set; }

    public virtual EmployeeDesignation Designation { get; set; }

    public virtual ICollection<InvoiceMaster> InvoiceMasters { get; set; } = new List<InvoiceMaster>();

    public virtual ICollection<OrderMaster> OrderMasters { get; set; } = new List<OrderMaster>();

    public virtual Person Person { get; set; }
}