// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class EmployeeDesignation
{
    public int Id { get; set; }

    public string Title { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}