// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class LaneAddress
{
    public int AddressId { get; set; }

    public string LaneAddressOne { get; set; }

    public string LaneAddressTwo { get; set; }

    public string Area { get; set; }

    public string FamousPlace { get; set; }

    public int? PersonId { get; set; }

    public int? CityId { get; set; }

    public string AddressType { get; set; }

    public virtual City City { get; set; }

    public virtual Person Person { get; set; }
}