// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Locality
{
    public int LocalityId { get; set; }

    public int CityId { get; set; }

    public string LocalityName { get; set; }

    public bool IsApproved { get; set; }

    public virtual City City { get; set; }

    public virtual ICollection<Reproperty> Reproperties { get; set; } = new List<Reproperty>();

    public virtual ICollection<SubLocality> SubLocalities { get; set; } = new List<SubLocality>();
}