// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class LoginUserDeviceDetail
{
    public int Id { get; set; }

    public string DeviceName { get; set; }

    public string DeviceIp { get; set; }

    public int? LoginUserId { get; set; }

    public virtual LoginUser LoginUser { get; set; }
}