// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class LoginHistory
{
    public int Id { get; set; }

    public DateTime? LastLogin { get; set; }

    public int? LoginUserId { get; set; }

    public virtual LoginUser LoginUser { get; set; }
}