// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class LoginUser
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public int? PersonId { get; set; }

    public int? SettingsId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public bool? IsDeleted { get; set; }

    public int? Createdby { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public virtual ICollection<AssignedRole> AssignedRoles { get; set; } = new List<AssignedRole>();

    public virtual ICollection<CmsemailSent> CmsemailSents { get; set; } = new List<CmsemailSent>();

    public virtual ICollection<Content> Contents { get; set; } = new List<Content>();

    public virtual ICollection<ErpPermission> ErpPermissions { get; set; } = new List<ErpPermission>();

    public virtual ICollection<FiscalPeriod> FiscalPeriods { get; set; } = new List<FiscalPeriod>();

    public virtual ICollection<JournalEntry> JournalEntryCreatedByNavigations { get; set; } = new List<JournalEntry>();

    public virtual ICollection<JournalEntry> JournalEntryUpdatedByNavigations { get; set; } = new List<JournalEntry>();

    public virtual ICollection<LoginHistory> LoginHistories { get; set; } = new List<LoginHistory>();

    public virtual ICollection<LoginUserDeviceDetail> LoginUserDeviceDetails { get; set; } = new List<LoginUserDeviceDetail>();

    public virtual Person Person { get; set; }

    public virtual ICollection<ProductReview> ProductReviews { get; set; } = new List<ProductReview>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual Setting Settings { get; set; }

    public virtual ICollection<UserAssignedBranch> UserAssignedBranches { get; set; } = new List<UserAssignedBranch>();
}