// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class SubLocality
{
    public int SubLocalityId { get; set; }

    public int LocalityId { get; set; }

    public string SubLocalityName { get; set; }

    public virtual Locality Locality { get; set; }

    public virtual ICollection<Reproperty> Reproperties { get; set; } = new List<Reproperty>();
}