// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Supplier
{
    public int SupplierId { get; set; }

    public string SupplierCode { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string Ntn { get; set; }

    public string CompanyLogo { get; set; }

    public int? PersonId { get; set; }

    public bool? IsActive { get; set; }

    public virtual Person Person { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}