// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class SupplierContact
{
    public int SpplierContactId { get; set; }

    public int? PersonId { get; set; }

    public int? SupplierId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Person Person { get; set; }

    public virtual Supplier Supplier { get; set; }
}