// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Supplier
{
    public int SupplierId { get; set; }

    public string SupplierBusinessName { get; set; }

    public string SupplierCode { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string Ntn { get; set; }

    public string CompanyLogo { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
    public virtual ICollection<PurchaseMaster> PurchaseMaster { get; set; } = new List<PurchaseMaster>();
    public virtual ICollection<SupplierContact> SupplierContacts { get; set; } = new List<SupplierContact>();
}