// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class UserAssignedBranch
{
    public int UserAssignedBranches { get; set; }

    public int? LoginUserId { get; set; }

    public Guid? BranchId { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public bool? IsDeleted { get; set; }

    public int? Createdby { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual LoginUser LoginUser { get; set; }
}