// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ClientLicense
{
    public int Id { get; set; }

    public string LicenseKey { get; set; }

    public string MachineFingerprint { get; set; }

    public DateTime? ValidFrom { get; set; }

    public DateTime? ValidTo { get; set; }

    public bool IsActive { get; set; }

    public string Signature { get; set; }

    public DateTime? CreatedAt { get; set; }
}