// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Device
{
    public int Id { get; set; }

    public Guid BranchId { get; set; }

    public string DeviceUniqueId { get; set; }

    public string DevicePayload { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Branch Branch { get; set; }
}