// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ErpPermission
{
    public int PermissionId { get; set; }

    public int? UserId { get; set; }

    public bool? CanView { get; set; }

    public bool? CanEdit { get; set; }

    public bool? CanDelete { get; set; }

    public bool? CanCreate { get; set; }

    public int? UrlMenuId { get; set; }

    public virtual UrlMenu UrlMenu { get; set; }

    public virtual LoginUser User { get; set; }
}