// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Notification
{
    public int Id { get; set; }

    public string Message { get; set; }

    public string Params { get; set; }

    public string UserId { get; set; }

    public string GroupName { get; set; }

    public bool IsRead { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? NotificationTypeId { get; set; }

    public virtual NotificationType NotificationType { get; set; }
}