// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class NotificationType
{
    public int NotificationTypeId { get; set; }

    public string NotificationTypeName { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();
}