// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ServiceLicense
{
    public int Id { get; set; }

    public string LicenseKey { get; set; }

    public string CustomerName { get; set; }

    public string DeviceId { get; set; }

    public string ProductName { get; set; }

    public DateTime ValidTill { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}