// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Setting
{
    public int SettingsId { get; set; }

    public int? ApplicationId { get; set; }

    public virtual ICollection<LoginUser> LoginUsers { get; set; } = new List<LoginUser>();
}