// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class UrlMenu
{
    public int UrlMenuId { get; set; }

    public string UrlMenuLink { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public virtual ICollection<ErpPermission> ErpPermissions { get; set; } = new List<ErpPermission>();
}