// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Website
{
    public int WebsiteId { get; set; }

    public string WebsiteName { get; set; }

    public string WebsiteLogo { get; set; }

    public string WebsiteLogoTwo { get; set; }

    public string FavIcon { get; set; }

    public string WebsiteDescription { get; set; }

    public string WebsiteTitle { get; set; }

    public string SupportEmail { get; set; }

    public virtual ICollection<CmsEmail> CmsEmails { get; set; } = new List<CmsEmail>();

    public virtual ICollection<Content> Contents { get; set; } = new List<Content>();

    public virtual ICollection<WebsiteDatum> WebsiteData { get; set; } = new List<WebsiteDatum>();
}