// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class WebsiteDatum
{
    public int WebsiteDataId { get; set; }

    public string Title { get; set; }

    public string Value { get; set; }

    public int WebsiteId { get; set; }

    public virtual Website Website { get; set; }
}