// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class AccountingPreference
{
    
    public string FiscalYearStartMonth { get; set; }

    public string FiscalYearEndMonth { get; set; }

    public DateTime? FiscalYearStartDate { get; set; }

    public DateTime? FiscalYearEndDate { get; set; }

    public bool EnableMultiCurrency { get; set; }

    public string BaseCurrencyCode { get; set; }

    public string DefaultExchangeRateSource { get; set; }

    public bool EnableAutomaticYearClosing { get; set; }

    public bool LockTransactionsAfterPeriodClose { get; set; }

    public string DefaultSalesAccount { get; set; }

    public string DefaultPurchaseAccount { get; set; }

    public string DefaultTaxAccount { get; set; }

    public bool AllowBackDatedTransactions { get; set; }

    public Guid AccountingPreferenceId { get; set; }

    public Guid BranchId { get; set; }

    public virtual Branch Branch { get; set; }
}