// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class SystemPreference
{
    public string CompanyName { get; set; }

    public bool IsRestaurantApplication { get; set; }

    public string CompanyLogoUrl { get; set; }

    public string DefaultLanguage { get; set; }

    public string TimeZone { get; set; }

    public string DateFormat { get; set; }

    public string CurrencyCode { get; set; }

    public string CurrencySymbol { get; set; }

    public int DecimalPlaces { get; set; }

    public bool IsAffilatedInvoice { get; set; }

    public bool EnableTax { get; set; }

    public decimal? DefaultTaxRate { get; set; }

    public string TaxRegistrationNumber { get; set; }

    public bool PricesIncludeTax { get; set; }

    public bool EnableInventoryTracking { get; set; }

    public string DefaultWarehouse { get; set; }

    public int? LowStockThreshold { get; set; }

    public bool AllowNegativeStock { get; set; }

    public string InvoicePrefix { get; set; }

    public int? InvoiceStartNumber { get; set; }

    public string QuotationPrefix { get; set; }

    public string ReceiptPrefix { get; set; }

    public bool ShowLogoOnInvoices { get; set; }

    public bool ShowTaxBreakdown { get; set; }

    public bool EnableTwoFactorAuth { get; set; }

    public int? SessionTimeoutMinutes { get; set; }

    public bool AllowMultipleLogins { get; set; }

    public string SmtpServer { get; set; }

    public int? SmtpPort { get; set; }

    public string SmtpUserName { get; set; }

    public string SmtpPassword { get; set; }

    public bool EnableSsl { get; set; }

    public string DefaultFromEmail { get; set; }

    public bool EnableAutoBackup { get; set; }

    public int? AutoBackupIntervalDays { get; set; }

    public string BackupLocation { get; set; }

    public Guid SystemPreferenceId { get; set; }

    public Guid BranchId { get; set; }

    public virtual Branch Branch { get; set; }
}