// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class AccountReceivable
{
    public Guid Arid { get; set; }

    public int CustomerId { get; set; }

    public int? InvoiceId { get; set; }

    public Guid? JournalEntryId { get; set; }

    public decimal Amount { get; set; }

    public decimal? ReceivedAmount { get; set; }

    public decimal? Balance { get; set; }

    public DateTime? DueDate { get; set; }

    public string Status { get; set; }

    public Guid BranchId { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual JournalEntry JournalEntry { get; set; }
}