// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class AccountBalance
{
    public Guid BalanceId { get; set; }

    public int CoaId { get; set; }

    public Guid BranchId { get; set; }

    public int FiscalYear { get; set; }

    public int FiscalPeriod { get; set; }

    public decimal? OpeningBalance { get; set; }

    public decimal? DebitTotal { get; set; }

    public decimal? CreditTotal { get; set; }

    public decimal? ClosingBalance { get; set; }

    public DateTime LastUpdated { get; set; }

    public virtual ChartOfAccount Coa { get; set; }
}