// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class AccountPayable
{
    public Guid Apid { get; set; }

    public int SupplierId { get; set; }

    public Guid? PurchaseId { get; set; }

    public Guid? JournalEntryId { get; set; }

    public decimal Amount { get; set; }

    public decimal? PaidAmount { get; set; }

    public decimal? Balance { get; set; }

    public DateTime? DueDate { get; set; }

    public string Status { get; set; }

    public Guid BranchId { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual JournalEntry JournalEntry { get; set; }
}