// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ChartOfAccount
{
    public int CoaId { get; set; }

    public string AccountCode { get; set; }

    public string AccountName { get; set; }

    public string AccountType { get; set; }

    public int? ParentCoaId { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<AccountBalance> AccountBalances { get; set; } = new List<AccountBalance>();

    public virtual ICollection<JournalLine> JournalLines { get; set; } = new List<JournalLine>();

    public virtual ICollection<TaxTransaction> TaxTransactions { get; set; } = new List<TaxTransaction>();
}