// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class FiscalPeriod
{
    public Guid FiscalPeriodId { get; set; }

    public int FiscalYear { get; set; }

    public int PeriodNumber { get; set; }

    public string PeriodName { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public bool? IsClosed { get; set; }

    public Guid BranchId { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual LoginUser CreatedByNavigation { get; set; }
}