// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class JournalLine
{
    public Guid JournalLineId { get; set; }

    public Guid JournalEntryId { get; set; }

    public int CoaId { get; set; }

    public string Description { get; set; }

    public decimal? Debit { get; set; }

    public decimal? Credit { get; set; }

    public Guid? ReferenceId { get; set; }

    public string ReferenceType { get; set; }

    public int? LineOrder { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ChartOfAccount Coa { get; set; }

    public virtual JournalEntry JournalEntry { get; set; }
}