// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class JournalEntry
{
    public Guid JournalEntryId { get; set; }

    public string EntryNumber { get; set; }

    public DateTime EntryDate { get; set; }

    public string ReferenceNumber { get; set; }

    public string Description { get; set; }

    public string SourceModule { get; set; }

    public Guid BranchId { get; set; }

    public decimal? TotalDebit { get; set; }

    public decimal? TotalCredit { get; set; }

    public string Status { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<AccountPayable> AccountPayables { get; set; } = new List<AccountPayable>();

    public virtual ICollection<AccountReceivable> AccountReceivables { get; set; } = new List<AccountReceivable>();

    public virtual LoginUser CreatedByNavigation { get; set; }

    public virtual ICollection<JournalLine> JournalLines { get; set; } = new List<JournalLine>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<TaxTransaction> TaxTransactions { get; set; } = new List<TaxTransaction>();

    public virtual LoginUser UpdatedByNavigation { get; set; }
}