// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Payment
{
    public Guid PaymentId { get; set; }

    public string PaymentType { get; set; }

    public string SourceType { get; set; }

    public int? SourceId { get; set; }

    public int? ReferenceId { get; set; }

    public Guid? JournalEntryId { get; set; }

    public string PaymentMode { get; set; }

    public decimal Amount { get; set; }

    public DateTime PaymentDate { get; set; }

    public Guid BranchId { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual JournalEntry JournalEntry { get; set; }
}