// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ReconciliationLog
{
    public Guid ReconciliationId { get; set; }

    public string SourceType { get; set; }

    public Guid? SourceId { get; set; }

    public string Description { get; set; }

    public decimal? AdjustmentAmount { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public Guid BranchId { get; set; }
}