// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class TaxTransaction
{
    public Guid TaxTransactionId { get; set; }

    public string SourceType { get; set; }

    public int SourceId { get; set; }

    public Guid? JournalEntryId { get; set; }

    public int TaxAccountId { get; set; }

    public decimal TaxRate { get; set; }

    public decimal TaxAmount { get; set; }

    public decimal BaseAmount { get; set; }

    public string TaxType { get; set; }

    public Guid BranchId { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual JournalEntry JournalEntry { get; set; }

    public virtual ChartOfAccount TaxAccount { get; set; }
}