// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Brand
{
    public Guid BrandId { get; set; }

    public string BrandName { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? Createdby { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public bool? IsDefault { get; set; }

    public string BrandSlug { get; set; }

    public virtual ICollection<BrandModel> BrandModels { get; set; } = new List<BrandModel>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}