// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class BrandModel
{
    public Guid BrandModelId { get; set; }

    public string ModelName { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public Guid BrandId { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}