// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Category
{
    public Guid CategoryId { get; set; }

    public string CategoryName { get; set; }

    public Guid? DepartmentId { get; set; }

    public Guid? BusinessStoreId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? Createdby { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Department1 Department { get; set; }

    public virtual ICollection<SubCategoryId> SubCategoryIds { get; set; } = new List<SubCategoryId>();
}