// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Category
{
    public Guid CategoryId { get; set; }

    public string CategoryName { get; set; }

    public Guid? DepartmentId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? Createdby { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public string CategorySlug { get; set; }

    public virtual ICollection<CouponCategory> CouponCategories { get; set; } = new List<CouponCategory>();

    public virtual Department Department { get; set; }

    public virtual ICollection<SubCategory> SubCategories { get; set; } = new List<SubCategory>();
}