// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class CollectionDetail
{
    public Guid CollectionDetailId { get; set; }

    public Guid CollectionId { get; set; }

    public Guid ProductId { get; set; }

    public Guid? VariantId { get; set; }

    public int? SortOrder { get; set; }

    public virtual CollectionMaster Collection { get; set; }

    public virtual Product Product { get; set; }

    public virtual ProductVariant Variant { get; set; }
}