// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class CouponCategory
{
    public Guid CouponCategoryId { get; set; }

    public Guid CouponId { get; set; }

    public Guid CategoryId { get; set; }

    public virtual Category Category { get; set; }

    public virtual Coupon Coupon { get; set; }
}