// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class CouponProduct
{
    public Guid CouponProductId { get; set; }

    public Guid CouponId { get; set; }

    public Guid ProductVariantId { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual ProductVariant ProductVariant { get; set; }
}