// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Coupon
{
    public Guid CouponId { get; set; }

    public string CouponCode { get; set; }

    public string CouponName { get; set; }

    public int? UsageLimitPerUser { get; set; }

    public int? MaxTotalUsage { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int? MinQuantity { get; set; }

    public decimal? MinCartAmount { get; set; }

    public string DiscountType { get; set; }

    public decimal DiscountValue { get; set; }

    public bool? AllowStacking { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual ICollection<CouponCategory> CouponCategories { get; set; } = new List<CouponCategory>();

    public virtual ICollection<CouponProduct> CouponProducts { get; set; } = new List<CouponProduct>();
}