// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Department
{
    public Guid DepartmentId { get; set; }

    public string DepartmentName { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? Createdby { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public string DepartmentSlug { get; set; }

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();
}