// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class InvoiceDetail
{
    public Guid InvoiceDetailId { get; set; }

    public Guid InvoiceMasterId { get; set; }

    public Guid ProductId { get; set; }

    public Guid? VariantId { get; set; }

    public decimal Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal? Discount { get; set; }

    public decimal? Tax { get; set; }

    public decimal? TotalAmount { get; set; }

    public string Remarks { get; set; }

    public virtual InvoiceMaster InvoiceMaster { get; set; }

    public virtual Product Product { get; set; }

    public virtual ProductVariant Variant { get; set; }
}