// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class InvoiceMaster
{
    public Guid InvoiceMasterId { get; set; }

    public string InvoiceNo { get; set; }

    public Guid? ParentInvoiceId { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public int? InvoiceSourceId { get; set; }

    public int? PaymentMethodId { get; set; }

    public int? PaymentStatusId { get; set; }

    public int? ShippingTypeId { get; set; }

    public Guid? CustomerId { get; set; }

    public int? EmployeeId { get; set; }

    public Guid? ServingTableId { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? GrandTotal { get; set; }

    public string CustomerRemarks { get; set; }

    public string OfficeRemarks { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? OrderStatusId { get; set; }

    public DateTime? DueDate { get; set; }

    public virtual ICollection<AccountReceivable> AccountReceivables { get; set; } = new List<AccountReceivable>();

    public virtual Customer Customer { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<InvoiceMaster> InverseParentInvoice { get; set; } = new List<InvoiceMaster>();

    public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; } = new List<InvoiceDetail>();

    public virtual InvoiceSource InvoiceSource { get; set; }

    public virtual OrderStatus OrderStatus { get; set; }

    public virtual InvoiceMaster ParentInvoice { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }

    public virtual PaymentStatus PaymentStatus { get; set; }

    public virtual ServingTable ServingTable { get; set; }

    public virtual ShippingType ShippingType { get; set; }
}