// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class OrderDetail
{
    public Guid OrderDetailId { get; set; }

    public Guid OrderMasterId { get; set; }

    public Guid ProductId { get; set; }

    public Guid VariantId { get; set; }

    public decimal? Quantity { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? TaxRate { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? LineTotal { get; set; }

    public decimal? LineTotalWithTax { get; set; }

    public decimal? Discount { get; set; }

    public string Remarks { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual OrderMaster OrderMaster { get; set; }

    public virtual Product Product { get; set; }

    public virtual ProductVariant Variant { get; set; }
}