// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class OrderMaster
{
    public Guid OrderMasterId { get; set; }

    public Guid? ParentOrderId { get; set; }

    public string OrderNo { get; set; }

    public DateTime OrderDate { get; set; }

    public int? OrderSourceId { get; set; }

    public int? PaymentMethodId { get; set; }

    public int? PaymentStatusId { get; set; }

    public int? ShippingTypeId { get; set; }

    public Guid? CustomerId { get; set; }

    public int? EmployeeId { get; set; }

    public Guid? ServingTableId { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? GrandTotal { get; set; }

    public string CustomerRemarks { get; set; }

    public string OfficeRemarks { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual ICollection<OrderMaster> InverseParentOrder { get; set; } = new List<OrderMaster>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual OrderMaster ParentOrder { get; set; }

    public virtual ServingTable ServingTable { get; set; }
}
