// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ProductVariant
{
    public Guid VariantId { get; set; }

    public Guid? MaterialId { get; set; }

    public Guid? ColorId { get; set; }

    public Guid? SizeId { get; set; }

    public Guid? ProductId { get; set; }

    public decimal? QoH { get; set; }

    public decimal? Cost { get; set; }

    public string BarCode { get; set; }

    public decimal? SalesPrice { get; set; }

    public decimal? PromotionPrice { get; set; }

    public decimal? RetailPrice { get; set; }

    public DateTime? LastPurchase { get; set; }

    public DateTime? LastSold { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? Createdby { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public Guid? VariantImageId { get; set; }

    public Guid? SubUomid { get; set; }

    public decimal? QuantityPerUnit { get; set; }

    public bool? IsSerial { get; set; }

    public int? MinQty { get; set; }

    public int? MaxQty { get; set; }

    public int? PriceFormat { get; set; }

    public virtual Color Color { get; set; }

    public virtual Material Material { get; set; }

    public virtual Product Product { get; set; }

    public virtual Size Size { get; set; }

    public virtual Uomsub SubUom { get; set; }
}