// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ProductReview
{
    public Guid ReviewId { get; set; }

    public Guid? ProductId { get; set; }

    public int? UserId { get; set; }

    public Guid? OrderId { get; set; }

    public byte Rating { get; set; }

    public string Title { get; set; }

    public string Comment { get; set; }

    public bool IsVerifiedPurchase { get; set; }

    public bool IsApproved { get; set; }

    public bool IsDeleted { get; set; }

    public int HelpfulCount { get; set; }

    public int NotHelpfulCount { get; set; }

    public string AdminReply { get; set; }

    public string Ipaddress { get; set; }

    public string UserAgent { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual OrderMaster Order { get; set; }

    public virtual Product Product { get; set; }

    public virtual LoginUser User { get; set; }
}