// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Product
{
    public Guid ProductId { get; set; }

    public string ProductName { get; set; }

    public string ProductDescription { get; set; }

    public decimal? Qoh { get; set; }

    public Guid? SubCategoryId { get; set; }

    public Guid? BranchId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? Createdby { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? SupplierId { get; set; }

    public string ProductSlug { get; set; }

    public Guid? Uomid { get; set; }

    public Guid? BrandId { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    public virtual ICollection<ProductVariant> ProductVariants { get; set; } = new List<ProductVariant>();

    public virtual SubCategory SubCategory { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual Uom Uom { get; set; }
}