// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ProductImage
{
    public Guid ProductImageId { get; set; }

    public string ImageUrl { get; set; }

    public string Caption { get; set; }

    public short? Priority { get; set; }

    public Guid? ProductId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? Createdby { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public bool? IsDefault { get; set; }

    public virtual Product Product { get; set; }
}