// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ProductBranch
{
    public Guid ProductBranchesId { get; set; }

    public Guid? ProductId { get; set; }

    public Guid? BranchId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? CreatedBy { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Product Product { get; set; }
}