// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ProductVariant
{
    public Guid VariantId { get; set; }

    public Guid? MaterialId { get; set; }

    public Guid? ColorId { get; set; }

    public Guid? SizeId { get; set; }

    public Guid? ProductId { get; set; }

    public Guid? Qty { get; set; }

    public decimal? Cost { get; set; }

    public decimal? SalesPrice { get; set; }

    public decimal? PromotionPrice { get; set; }

    public decimal? RetailPrice { get; set; }

    public DateTime? LastPurchase { get; set; }

    public DateTime? LastSold { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? Createdby { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public Guid? BranchId { get; set; }

    public Guid? ProductImageId { get; set; }

    public Guid? Uomid { get; set; }

    public Guid? SubUomid { get; set; }

    public virtual Color Color { get; set; }

    public virtual Material Material { get; set; }

    public virtual Product Product { get; set; }

    public virtual Size Size { get; set; }

    public virtual Uom Uom { get; set; }

    public virtual Uomsub Uomsub { get; set; }
}