// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class PurchaseMaster
{
    public Guid PurchaseMasterId { get; set; }

    public string PurchaseNumber { get; set; }

    public int? PurchaseType { get; set; }

    public int? SupplierId { get; set; }

    public DateTime? PurchaseDate { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? GrandTotal { get; set; }

    public int? Status { get; set; }

    public string Remarks { get; set; }

    public Guid? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? Createdby { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public Guid? BranchId { get; set; }

    public int? OrganizationId { get; set; }


    public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; } = new List<PurchaseDetail>();

    public virtual Supplier Supplier { get; set; }
}