// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class PurchaseDetail
{
    public Guid PurchaseDetailId { get; set; }

    public Guid PurchaseMasterId { get; set; }

    public Guid? VariantId { get; set; }

    public decimal? Qty { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? TotalPrice { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? LineTotal { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? Createdby { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public virtual PurchaseMaster PurchaseMaster { get; set; }

    public virtual ProductVariant Variant { get; set; }
}
