// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Uomsub
{
    public Guid SubUomid { get; set; }

    public Guid? Uomid { get; set; }

    public string SubUomname { get; set; }

    public decimal? ConversionFactor { get; set; }

    public Guid? BranchId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? Createdby { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<ProductVariant> ProductVariants { get; set; } = new List<ProductVariant>();

    public virtual Uom Uom { get; set; }
}