// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class CmsContentSharedCategory
{
    public int Id { get; set; }

    public int? ContentId { get; set; }

    public int? CategoryId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual ContentCategory Category { get; set; }

    public virtual Content Content { get; set; }
}