// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class CmsEmail
{
    public int EmailId { get; set; }

    public int? WebsiteId { get; set; }

    public string EmailSubject { get; set; }

    public string EmailSender { get; set; }

    public string EmailBody { get; set; }

    public DateTime? DateCreated { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string FullName { get; set; }

    public string Mobile { get; set; }

    public string LandLine { get; set; }

    public bool? IsSend { get; set; }

    public string StatusMessage { get; set; }

    public bool? IsRead { get; set; }

    public virtual ICollection<CmsemailSent> CmsemailSents { get; set; } = new List<CmsemailSent>();

    public virtual Website Website { get; set; }
}