// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class CmsemailSent
{
    public int EmailSentId { get; set; }

    public string ToEmailAddress { get; set; }

    public string FromEmailAddress { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public DateTime SentDateTime { get; set; }

    public bool IsSent { get; set; }

    public bool IsRead { get; set; }

    public int? UserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? EmailId { get; set; }

    public virtual CmsEmail Email { get; set; }

    public virtual LoginUser EmailNavigation { get; set; }
}