// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Comment
{
    public int CommentId { get; set; }

    public string Comment1 { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? LoginUser { get; set; }

    public bool? IsPublished { get; set; }

    public int? ApprovedBy { get; set; }

    public string UserIp { get; set; }

    public string UserBrowser { get; set; }

    public int? ReviewId { get; set; }

    public virtual Review Review { get; set; }
}