// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ContentCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int TypeId { get; set; }

    public string CreatedOn { get; set; }

    public string Slug { get; set; }

    public string ImageUrl { get; set; }

    public string ShortDescription { get; set; }

    public string Description { get; set; }

    public string Icon { get; set; }

    public virtual ICollection<CmsContentSharedCategory> CmsContentSharedCategories { get; set; } = new List<CmsContentSharedCategory>();

    public virtual ContentType Type { get; set; }
}