// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Content
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Tagline { get; set; }

    public string OverView { get; set; }

    public string VideoLink { get; set; }

    public string Note { get; set; }

    public string Description { get; set; }

    public string ImageSource { get; set; }

    public string Thumbnail { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? WebSiteId { get; set; }

    public int? ContentTypeId { get; set; }

    public string OtherTitle { get; set; }

    public string MetaDescription { get; set; }

    public string ShortDescription { get; set; }

    public string OtherShortDescription { get; set; }

    public string OtherDescription { get; set; }

    public int? Priority { get; set; }

    public string Icon { get; set; }

    public string MetaTitle { get; set; }

    public string HeaderPhoto { get; set; }

    public string ContentSlug { get; set; }

    public string FwdUrl { get; set; }

    public string MetaKeyword { get; set; }

    public int? ParentId { get; set; }

    public DateTime? Date { get; set; }

    public int? LoginUserId { get; set; }

    public string Ipaddress { get; set; }

    public bool? IsPublished { get; set; }

    public virtual ICollection<CmsContentSharedCategory> CmsContentSharedCategories { get; set; } = new List<CmsContentSharedCategory>();

    public virtual ContentType ContentType { get; set; }

    public virtual ICollection<FileManager> FileManagers { get; set; } = new List<FileManager>();

    public virtual ICollection<LinkedContentItem> LinkedContentItemContents { get; set; } = new List<LinkedContentItem>();

    public virtual ICollection<LinkedContentItem> LinkedContentItemLinkedContents { get; set; } = new List<LinkedContentItem>();

    public virtual LoginUser LoginUser { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual Website WebSite { get; set; }
}