// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ContentType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string TypeSlug { get; set; }

    public virtual ICollection<ContentCategory> ContentCategories { get; set; } = new List<ContentCategory>();

    public virtual ICollection<Content> Contents { get; set; } = new List<Content>();
}