// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class LinkedContentItem
{
    public int LinkedItemId { get; set; }

    public int? LinkedContentId { get; set; }

    public int? ContentId { get; set; }

    public int? Priority { get; set; }

    public virtual Content Content { get; set; }

    public virtual Content LinkedContent { get; set; }
}