// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public string ReviewComment { get; set; }

    public short? Rating { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? LoginUserId { get; set; }

    public bool? IsPublished { get; set; }

    public int? ApprovedBy { get; set; }

    public string UserIp { get; set; }

    public string UserBrowser { get; set; }

    public int? ContentId { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual Content Content { get; set; }

    public virtual LoginUser LoginUser { get; set; }
}