// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Subscriber
{
    public int SubscriberId { get; set; }

    public string Email { get; set; }

    public bool? WantsEmailNewsletter { get; set; }

    public bool? WantsWhatsappNewsletter { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string PhoneNumber { get; set; }

    public string City { get; set; }

    public string Country { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastModifiedDate { get; set; }

    public string Ipaddress { get; set; }

    public bool? IsActive { get; set; }
}