// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Branch
{
    public Guid BranchId { get; set; }

    public string BranchName { get; set; }

    public int? OrganizationId { get; set; }

    public short? BusinessCategoryId { get; set; }

    public int? BusinessStoreTypeId { get; set; }

    public short? BusinessEntityTypeId { get; set; }

    public string BranchCode { get; set; }

    public virtual ICollection<AccountingPreference> AccountingPreferences { get; set; } = new List<AccountingPreference>();

    public virtual ICollection<Building> Buildings { get; set; } = new List<Building>();

    public virtual BusinessCategory BusinessCategory { get; set; }

    public virtual BusinessStoreType BusinessCategoryNavigation { get; set; }

    public virtual BusinessEntityType BusinessEntityType { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual ICollection<Person> People { get; set; } = new List<Person>();

    public virtual ICollection<ProductBranch> ProductBranches { get; set; } = new List<ProductBranch>();

    public virtual ICollection<SystemPreference> SystemPreferences { get; set; } = new List<SystemPreference>();

    public virtual ICollection<UserAssignedBranch> UserAssignedBranches { get; set; } = new List<UserAssignedBranch>();
}