// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ProjectColumn
{
    public Guid ColumnId { get; set; }

    public Guid? ProjectId { get; set; }

    public string ColumnName { get; set; }

    public int? SortOrder { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsModified { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual Project Project { get; set; }

    public virtual ICollection<ProjectTask> ProjectTasks { get; set; } = new List<ProjectTask>();
}