// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ProjectTask
{
    public Guid TaskId { get; set; }

    public Guid? ProjectId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? TaskNumber { get; set; }

    public string Priority { get; set; }

    public string Status { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? DueDate { get; set; }

    public decimal? EstimatedHours { get; set; }

    public decimal? ActualHours { get; set; }

    public int? SortOrder { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsModified { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public Guid? ColumnId { get; set; }

    public virtual ProjectColumn Column { get; set; }

    public virtual ICollection<TaskAssignedUser> TaskAssignedUsers { get; set; } = new List<TaskAssignedUser>();

    public virtual ICollection<TaskAttachment> TaskAttachments { get; set; } = new List<TaskAttachment>();

    public virtual ICollection<TaskComment> TaskComments { get; set; } = new List<TaskComment>();
}