// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Project
{
    public Guid ProjectId { get; set; }

    public Guid? BranchId { get; set; }

    public string ProjectName { get; set; }

    public string ProjectCode { get; set; }

    public string Description { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string ColorCode { get; set; }

    public string Icon { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsModified { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<ProjectColumn> ProjectColumns { get; set; } = new List<ProjectColumn>();

    public virtual ICollection<ProjectUser> ProjectUsers { get; set; } = new List<ProjectUser>();
}