// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ProjectUser
{
    public Guid ProjectUserId { get; set; }

    public Guid? ProjectId { get; set; }

    public int? UserId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Project Project { get; set; }

    public virtual LoginUser User { get; set; }
}