// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ProjectNotificationEmail
{
    public Guid ProjectNotificationEmailId { get; set; }

    public int? UserId { get; set; }

    public short? ProjectEmailNotificationType { get; set; }

    public bool IsSent { get; set; }

    public bool? IsRead { get; set; }

    public string MessageJson { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual LoginUser User { get; set; }
}