// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class TaskAssignedUser
{
    public Guid TaskAssignedUserId { get; set; }

    public Guid? TaskId { get; set; }

    public DateTime? AssignedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsModified { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? UserId { get; set; }

    public virtual ProjectTask Task { get; set; }

    public virtual LoginUser User { get; set; }
}