// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class TaskComment
{
    public Guid TaskCommentId { get; set; }

    public string TaskComments { get; set; }

    public Guid? TaskId { get; set; }

    public int? UserId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ProjectTask Task { get; set; }
}