// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MainModels.Models;

public partial class OneDb : DbContext
{
    public OneDb(DbContextOptions<OneDb> options)
        : base(options)
    {
    }

    public virtual DbSet<AccountBalance> AccountBalances { get; set; }

    public virtual DbSet<AccountPayable> AccountPayables { get; set; }

    public virtual DbSet<AccountReceivable> AccountReceivables { get; set; }

    public virtual DbSet<AccountingPreference> AccountingPreferences { get; set; }

    public virtual DbSet<AssignedRole> AssignedRoles { get; set; }

    public virtual DbSet<Branch> Branches { get; set; }

    public virtual DbSet<BranchStock> BranchStocks { get; set; }

    public virtual DbSet<Brand> Brands { get; set; }

    public virtual DbSet<BrandModel> BrandModels { get; set; }

    public virtual DbSet<Building> Buildings { get; set; }

    public virtual DbSet<BusinessCategory> BusinessCategories { get; set; }

    public virtual DbSet<BusinessEntityType> BusinessEntityTypes { get; set; }

    public virtual DbSet<BusinessStoreType> BusinessStoreTypes { get; set; }

    public virtual DbSet<CartDetail> CartDetails { get; set; }

    public virtual DbSet<CartMaster> CartMasters { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<ChartOfAccount> ChartOfAccounts { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<CmsContentSharedCategory> CmsContentSharedCategories { get; set; }

    public virtual DbSet<CmsEmail> CmsEmails { get; set; }

    public virtual DbSet<CmsemailSent> CmsemailSents { get; set; }

    public virtual DbSet<CollectionDetail> CollectionDetails { get; set; }

    public virtual DbSet<CollectionMaster> CollectionMasters { get; set; }

    public virtual DbSet<Color> Colors { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<Content> Contents { get; set; }

    public virtual DbSet<ContentCategory> ContentCategories { get; set; }

    public virtual DbSet<ContentType> ContentTypes { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<EmployeeDepartment> EmployeeDepartments { get; set; }

    public virtual DbSet<EmployeeDesignation> EmployeeDesignations { get; set; }

    public virtual DbSet<ErpPermission> ErpPermissions { get; set; }

    public virtual DbSet<FileManager> FileManagers { get; set; }

    public virtual DbSet<FiscalPeriod> FiscalPeriods { get; set; }

    public virtual DbSet<Floor> Floors { get; set; }

    public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }

    public virtual DbSet<InvoiceMaster> InvoiceMasters { get; set; }

    public virtual DbSet<InvoiceSource> InvoiceSources { get; set; }

    public virtual DbSet<JournalEntry> JournalEntries { get; set; }

    public virtual DbSet<JournalLine> JournalLines { get; set; }

    public virtual DbSet<LaneAddress> LaneAddresses { get; set; }

    public virtual DbSet<LinkedContentItem> LinkedContentItems { get; set; }

    public virtual DbSet<LoginHistory> LoginHistories { get; set; }

    public virtual DbSet<LoginUser> LoginUsers { get; set; }

    public virtual DbSet<LoginUserDeviceDetail> LoginUserDeviceDetails { get; set; }

    public virtual DbSet<Material> Materials { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<NotificationType> NotificationTypes { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<OrderMaster> OrderMasters { get; set; }

    public virtual DbSet<OrderStatus> OrderStatuses { get; set; }

    public virtual DbSet<Organization> Organizations { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<PaymentStatus> PaymentStatuses { get; set; }

    public virtual DbSet<Person> Persons { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductBranch> ProductBranches { get; set; }

    public virtual DbSet<ProductImage> ProductImages { get; set; }

    public virtual DbSet<ProductVariant> ProductVariants { get; set; }

    public virtual DbSet<PurchaseDetail> PurchaseDetails { get; set; }

    public virtual DbSet<PurchaseMaster> PurchaseMasters { get; set; }

    public virtual DbSet<ReconciliationLog> ReconciliationLogs { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<ServingTable> ServingTables { get; set; }

    public virtual DbSet<Setting> Settings { get; set; }

    public virtual DbSet<ShippingType> ShippingTypes { get; set; }

    public virtual DbSet<Size> Sizes { get; set; }

    public virtual DbSet<StateProvince> StateProvinces { get; set; }

    public virtual DbSet<SubCategory> SubCategories { get; set; }

    public virtual DbSet<Supplier> Suppliers { get; set; }

    public virtual DbSet<SupplierContact> SupplierContacts { get; set; }

    public virtual DbSet<SystemPreference> SystemPreferences { get; set; }

    public virtual DbSet<TaxSlab> TaxSlabs { get; set; }

    public virtual DbSet<TaxTransaction> TaxTransactions { get; set; }

    public virtual DbSet<Uom> Uoms { get; set; }

    public virtual DbSet<Uomsub> Uomsubs { get; set; }

    public virtual DbSet<UrlMenu> UrlMenus { get; set; }

    public virtual DbSet<UserAssignedBranch> UserAssignedBranches { get; set; }

    public virtual DbSet<Website> Websites { get; set; }

    public virtual DbSet<WebsiteDatum> WebsiteData { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AccountBalance>(entity =>
        {
            entity.HasKey(e => e.BalanceId).HasName("PK__AccountB__A760D5BEFF817707");

            entity.ToTable("AccountBalances", "Accounting");

            entity.Property(e => e.BalanceId).ValueGeneratedNever();
            entity.Property(e => e.ClosingBalance)
                .HasComputedColumnSql("(([OpeningBalance]+[DebitTotal])-[CreditTotal])", true)
                .HasColumnType("decimal(20, 2)");
            entity.Property(e => e.CreditTotal)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DebitTotal)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.OpeningBalance)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Coa).WithMany(p => p.AccountBalances)
                .HasForeignKey(d => d.CoaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AccountBa__CoaId__3572E547");
        });

        modelBuilder.Entity<AccountPayable>(entity =>
        {
            entity.HasKey(e => e.Apid).HasName("PK__AccountP__4C29F34F4F4C8EDA");

            entity.ToTable("AccountPayables", "Accounting");

            entity.Property(e => e.Apid)
                .ValueGeneratedNever()
                .HasColumnName("APId");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Balance)
                .HasComputedColumnSql("([Amount]-[PaidAmount])", true)
                .HasColumnType("decimal(19, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DueDate).HasColumnType("date");
            entity.Property(e => e.PaidAmount)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Pending");

            entity.HasOne(d => d.JournalEntry).WithMany(p => p.AccountPayables)
                .HasForeignKey(d => d.JournalEntryId)
                .HasConstraintName("FK__AccountPa__Journ__40E497F3");

            entity.HasOne(d => d.Supplier).WithMany(p => p.AccountPayables)
                .HasForeignKey(d => d.SupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AccountPayables_Supplier");
        });

        modelBuilder.Entity<AccountReceivable>(entity =>
        {
            entity.HasKey(e => e.Arid).HasName("PK__AccountR__4CB5C49BB3B78494");

            entity.ToTable("AccountReceivables", "Accounting");

            entity.Property(e => e.Arid)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ARId");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Balance)
                .HasComputedColumnSql("([Amount]-[ReceivedAmount])", true)
                .HasColumnType("decimal(19, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DueDate).HasColumnType("date");
            entity.Property(e => e.ReceivedAmount)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Pending");

            entity.HasOne(d => d.Customer).WithMany(p => p.AccountReceivables)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AccountRe__Custo__61516785");

            entity.HasOne(d => d.Invoice).WithMany(p => p.AccountReceivables)
                .HasForeignKey(d => d.InvoiceId)
                .HasConstraintName("FK__AccountRe__Invoi__62458BBE");

            entity.HasOne(d => d.JournalEntry).WithMany(p => p.AccountReceivables)
                .HasForeignKey(d => d.JournalEntryId)
                .HasConstraintName("FK__AccountRe__Journ__6339AFF7");
        });

        modelBuilder.Entity<AccountingPreference>(entity =>
        {
            entity.HasKey(e => e.AccountingPreferenceId).HasName("PK_AccountingPreferences_Id");

            entity.ToTable("AccountingPreferences", "Setup");

            entity.Property(e => e.AccountingPreferenceId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.BaseCurrencyCode).HasMaxLength(10);
            entity.Property(e => e.DefaultExchangeRateSource).HasMaxLength(50);
            entity.Property(e => e.DefaultPurchaseAccount).HasMaxLength(100);
            entity.Property(e => e.DefaultSalesAccount).HasMaxLength(100);
            entity.Property(e => e.DefaultTaxAccount).HasMaxLength(100);
            entity.Property(e => e.FiscalYearEndDate).HasColumnType("date");
            entity.Property(e => e.FiscalYearEndMonth).HasMaxLength(20);
            entity.Property(e => e.FiscalYearStartDate).HasColumnType("date");
            entity.Property(e => e.FiscalYearStartMonth).HasMaxLength(20);

            entity.HasOne(d => d.Branch).WithMany(p => p.AccountingPreferences)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AccountingPreferences_Branch");
        });

        modelBuilder.Entity<AssignedRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Assigned__3214EC079F2A4CCC");

            entity.ToTable("AssignedRoles", "SYSTEM");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Login).WithMany(p => p.AssignedRoles)
                .HasForeignKey(d => d.LoginId)
                .HasConstraintName("FK__AssignedR__Login__3587F3E0");

            entity.HasOne(d => d.Role).WithMany(p => p.AssignedRoles)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK__AssignedR__RoleI__367C1819");
        });

        modelBuilder.Entity<Branch>(entity =>
        {
            entity.ToTable("Branches", "Business");

            entity.Property(e => e.BranchId).ValueGeneratedNever();
            entity.Property(e => e.BranchCode)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.BranchName).HasMaxLength(500);
            entity.Property(e => e.IsMasterBranch).HasDefaultValue(false);

            entity.HasOne(d => d.BusinessCategory).WithMany(p => p.Branches)
                .HasForeignKey(d => d.BusinessCategoryId)
                .HasConstraintName("FK_Branches_BusinessCategory");

            entity.HasOne(d => d.BusinessEntityType).WithMany(p => p.Branches)
                .HasForeignKey(d => d.BusinessEntityTypeId)
                .HasConstraintName("FK_Branches_BusinessEntityType");

            entity.HasOne(d => d.BusinessStoreType).WithMany(p => p.Branches)
                .HasForeignKey(d => d.BusinessStoreTypeId)
                .HasConstraintName("FK_Branches_BusinessStoreType");

            entity.HasOne(d => d.Organization).WithMany(p => p.Branches)
                .HasForeignKey(d => d.OrganizationId)
                .HasConstraintName("FK_Branches_Organizations");
        });

        modelBuilder.Entity<BranchStock>(entity =>
        {
            entity.HasKey(e => e.BranchStockId).HasName("PK__BranchSt__13C9002F0FFED5A1");

            entity.ToTable("BranchStock", "INV");

            entity.HasIndex(e => e.BranchId, "IX_BranchStock_Branch");

            entity.HasIndex(e => e.ProductVariantId, "IX_BranchStock_ProductVariant");

            entity.Property(e => e.BranchStockId).ValueGeneratedNever();
            entity.Property(e => e.Cost).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LastSold).HasColumnType("datetime");
            entity.Property(e => e.PromotionPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Qty).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.RetailPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SalePrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.StaffPrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Branch).WithMany(p => p.BranchStocks)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("FK_BranchStock_Branch");

            entity.HasOne(d => d.ProductVariant).WithMany(p => p.BranchStocks)
                .HasForeignKey(d => d.ProductVariantId)
                .HasConstraintName("FK_BranchStock_ProductVariant");
        });

        modelBuilder.Entity<Brand>(entity =>
        {
            entity.ToTable("Brands", "INV");

            entity.Property(e => e.BrandId).ValueGeneratedNever();
            entity.Property(e => e.BrandName).HasMaxLength(500);
            entity.Property(e => e.BrandSlug).HasMaxLength(500);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<BrandModel>(entity =>
        {
            entity.HasKey(e => e.BrandModelId).HasName("PK__BrandMod__6981FE0A6582C4BF");

            entity.ToTable("BrandModels", "INV");

            entity.Property(e => e.BrandModelId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ModelName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Brand).WithMany(p => p.BrandModels)
                .HasForeignKey(d => d.BrandId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BrandModels_Brands");
        });

        modelBuilder.Entity<Building>(entity =>
        {
            entity.ToTable("Buildings", "AST");

            entity.Property(e => e.BuildingId).ValueGeneratedNever();
            entity.Property(e => e.BuildingName).HasMaxLength(500);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Branch).WithMany(p => p.Buildings)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("FK_Buildings_Branches");
        });

        modelBuilder.Entity<BusinessCategory>(entity =>
        {
            entity.HasKey(e => e.BusinessCategoryId).HasName("PK__Business__4024A26D5C2BB52F");

            entity.ToTable("BusinessCategory", "Business");

            entity.Property(e => e.BusinessCategoryId).ValueGeneratedNever();
            entity.Property(e => e.BusinessCategoryName).HasMaxLength(500);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<BusinessEntityType>(entity =>
        {
            entity.HasKey(e => e.BusinessEntityTypeId).HasName("PK__Business__837393DA16DC05EE");

            entity.ToTable("BusinessEntityType", "Business");

            entity.Property(e => e.BusinessEntityTypeId).ValueGeneratedNever();
            entity.Property(e => e.BusinessEntityTypeName).HasMaxLength(500);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<BusinessStoreType>(entity =>
        {
            entity.HasKey(e => e.BusinessStoreTypeId).HasName("PK__Business__673FC7EDA67B78A0");

            entity.ToTable("BusinessStoreType", "Business");

            entity.Property(e => e.BusinessStoreTypeId).ValueGeneratedNever();
            entity.Property(e => e.BusinessStoreTypeName).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<CartDetail>(entity =>
        {
            entity.HasKey(e => e.CartDetailId).HasName("PK__CartDeta__01B6A6B406F29BBA");

            entity.ToTable("CartDetail", "INV");

            entity.Property(e => e.CartDetailId).ValueGeneratedNever();
            entity.Property(e => e.Discount)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Quantity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Tax)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAmount)
                .HasComputedColumnSql("(([Quantity]*[UnitPrice]-[Discount])+[Tax])", true)
                .HasColumnType("decimal(38, 4)");
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Cart).WithMany(p => p.CartDetails)
                .HasForeignKey(d => d.CartId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartDetai__CartI__02925FBF");

            entity.HasOne(d => d.Product).WithMany(p => p.CartDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartDetai__Produ__038683F8");

            entity.HasOne(d => d.Variant).WithMany(p => p.CartDetails)
                .HasForeignKey(d => d.VariantId)
                .HasConstraintName("FK__CartDetai__Varia__047AA831");
        });

        modelBuilder.Entity<CartMaster>(entity =>
        {
            entity.HasKey(e => e.CartId).HasName("PK__CartMast__51BCD7B7F938D4BF");

            entity.ToTable("CartMaster", "INV");

            entity.Property(e => e.CartId).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsCheckedOut).HasDefaultValue(false);
            entity.Property(e => e.SessionId)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.ToTable("Categories", "INV");

            entity.Property(e => e.CategoryId).ValueGeneratedNever();
            entity.Property(e => e.CategoryName).HasMaxLength(1000);
            entity.Property(e => e.CategorySlug).HasMaxLength(500);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Department).WithMany(p => p.Categories)
                .HasForeignKey(d => d.DepartmentId)
                .HasConstraintName("FK_Categories_Departments");
        });

        modelBuilder.Entity<ChartOfAccount>(entity =>
        {
            entity.HasKey(e => e.CoaId).HasName("PK__ChartOfA__FA4C03A7DA9218BC");

            entity.ToTable("ChartOfAccounts", "Accounting");

            entity.HasIndex(e => e.AccountCode, "UQ__ChartOfA__38D0C56ACB837515").IsUnique();

            entity.Property(e => e.AccountCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.AccountName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.AccountType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<City>(entity =>
        {
            entity.HasKey(e => e.CityId).HasName("PK__Cities__F2D21B764D606662");

            entity.ToTable("Cities", "HRM");

            entity.Property(e => e.CityId).ValueGeneratedNever();
            entity.Property(e => e.CityName).HasMaxLength(1000);

            entity.HasOne(d => d.StateProvince).WithMany(p => p.Cities)
                .HasForeignKey(d => d.StateProvinceId)
                .HasConstraintName("FK_Cities_StateProvince");
        });

        modelBuilder.Entity<CmsContentSharedCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CmsConte__3214EC073ACDA7FC");

            entity.ToTable("CmsContentSharedCategory", "WEBCMS");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Category).WithMany(p => p.CmsContentSharedCategories)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK__CmsConten__Categ__3A4CA8FD");

            entity.HasOne(d => d.Content).WithMany(p => p.CmsContentSharedCategories)
                .HasForeignKey(d => d.ContentId)
                .HasConstraintName("FK__CmsConten__Conte__3B40CD36");
        });

        modelBuilder.Entity<CmsEmail>(entity =>
        {
            entity.HasKey(e => e.EmailId).HasName("PK__CmsEmail__7ED91ACF12AA153A");

            entity.ToTable("CmsEmail", "WEBCMS");

            entity.Property(e => e.EmailId).ValueGeneratedNever();
            entity.Property(e => e.DateCreated).HasColumnType("date");
            entity.Property(e => e.EmailSender).HasMaxLength(500);
            entity.Property(e => e.EmailSubject).HasMaxLength(500);
            entity.Property(e => e.FirstName).HasMaxLength(500);
            entity.Property(e => e.FullName).HasMaxLength(500);
            entity.Property(e => e.LandLine).HasMaxLength(500);
            entity.Property(e => e.LastName).HasMaxLength(500);
            entity.Property(e => e.Mobile).HasMaxLength(500);
            entity.Property(e => e.StatusMessage).HasMaxLength(500);

            entity.HasOne(d => d.Website).WithMany(p => p.CmsEmails)
                .HasForeignKey(d => d.WebsiteId)
                .HasConstraintName("FK__CmsEmail__Websit__3C34F16F");
        });

        modelBuilder.Entity<CmsemailSent>(entity =>
        {
            entity.HasKey(e => e.EmailSentId).HasName("PK__CMSEmail__456E5F9B17DB4AF3");

            entity.ToTable("CMSEmailSent", "WEBCMS");

            entity.Property(e => e.EmailSentId).ValueGeneratedNever();
            entity.Property(e => e.Body).IsRequired();
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.FromEmailAddress)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.SentDateTime).HasColumnType("datetime");
            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.ToEmailAddress)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Email).WithMany(p => p.CmsemailSents)
                .HasForeignKey(d => d.EmailId)
                .HasConstraintName("FK__CMSEmailS__Email__3D2915A8");

            entity.HasOne(d => d.EmailNavigation).WithMany(p => p.CmsemailSents)
                .HasForeignKey(d => d.EmailId)
                .HasConstraintName("FK__CMSEmailS__Email__3E1D39E1");
        });

        modelBuilder.Entity<CollectionDetail>(entity =>
        {
            entity.HasKey(e => e.CollectionDetailId).HasName("PK__Collecti__944C6E15B085EF5D");

            entity.ToTable("CollectionDetail", "INV");

            entity.Property(e => e.CollectionDetailId).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Collection).WithMany(p => p.CollectionDetails)
                .HasForeignKey(d => d.CollectionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CollectionDetail_CollectionMaster1");

            entity.HasOne(d => d.Product).WithMany(p => p.CollectionDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_CollectionDetail_Product");

            entity.HasOne(d => d.Variant).WithMany(p => p.CollectionDetails)
                .HasForeignKey(d => d.VariantId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_CollectionDetail_Variant");
        });

        modelBuilder.Entity<CollectionMaster>(entity =>
        {
            entity.HasKey(e => e.CollectionId).HasName("PK__Collecti__7DE6BC048291CABC");

            entity.ToTable("CollectionMaster", "INV");

            entity.Property(e => e.CollectionId).ValueGeneratedNever();
            entity.Property(e => e.CollectionName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasMaxLength(500);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<Color>(entity =>
        {
            entity.ToTable("Colors", "INV");

            entity.Property(e => e.ColorId).ValueGeneratedNever();
            entity.Property(e => e.ColorName).HasMaxLength(500);
            entity.Property(e => e.ColorSlug).HasMaxLength(500);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<Comment>(entity =>
        {
            entity.HasKey(e => e.CommentId).HasName("PK__Comments__C3B4DFCAC79F5C92");

            entity.ToTable("Comments", "WEBCMS");

            entity.Property(e => e.CommentId).ValueGeneratedNever();
            entity.Property(e => e.Comment1)
                .HasMaxLength(1000)
                .HasColumnName("Comment");
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.UserBrowser).HasMaxLength(50);
            entity.Property(e => e.UserIp)
                .HasMaxLength(50)
                .HasColumnName("UserIP");

            entity.HasOne(d => d.Review).WithMany(p => p.Comments)
                .HasForeignKey(d => d.ReviewId)
                .HasConstraintName("FK__Comments__Review__3F115E1A");
        });

        modelBuilder.Entity<Content>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Content__3214EC0768F46D1C");

            entity.ToTable("Content", "WEBCMS");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ContentSlug).HasMaxLength(1000);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Date).HasColumnType("date");
            entity.Property(e => e.FwdUrl).HasMaxLength(800);
            entity.Property(e => e.HeaderPhoto).HasMaxLength(500);
            entity.Property(e => e.Icon).HasMaxLength(50);
            entity.Property(e => e.ImageSource).HasMaxLength(500);
            entity.Property(e => e.Ipaddress).HasMaxLength(500);
            entity.Property(e => e.MetaDescription).HasMaxLength(1500);
            entity.Property(e => e.MetaKeyword).HasMaxLength(1500);
            entity.Property(e => e.MetaTitle).HasMaxLength(1500);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(1000);
            entity.Property(e => e.Note).HasMaxLength(1000);
            entity.Property(e => e.OtherTitle).HasMaxLength(1500);
            entity.Property(e => e.Tagline).HasMaxLength(1000);
            entity.Property(e => e.Thumbnail).HasMaxLength(500);
            entity.Property(e => e.VideoLink).HasMaxLength(500);

            entity.HasOne(d => d.ContentType).WithMany(p => p.Contents)
                .HasForeignKey(d => d.ContentTypeId)
                .HasConstraintName("FK__Content__Content__40058253");

            entity.HasOne(d => d.LoginUser).WithMany(p => p.Contents)
                .HasForeignKey(d => d.LoginUserId)
                .HasConstraintName("FK__Content__LoginUs__40F9A68C");

            entity.HasOne(d => d.WebSite).WithMany(p => p.Contents)
                .HasForeignKey(d => d.WebSiteId)
                .HasConstraintName("FK__Content__WebSite__41EDCAC5");
        });

        modelBuilder.Entity<ContentCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ContentC__3214EC07ACE3C490");

            entity.ToTable("ContentCategory", "WEBCMS");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasMaxLength(50);
            entity.Property(e => e.Name).HasMaxLength(501);
            entity.Property(e => e.Slug).HasMaxLength(501);

            entity.HasOne(d => d.Type).WithMany(p => p.ContentCategories)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContentCategory_ContentType");
        });

        modelBuilder.Entity<ContentType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ContentT__3214EC07422DDA5D");

            entity.ToTable("ContentType", "WEBCMS");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.TypeSlug).HasMaxLength(100);
        });

        modelBuilder.Entity<Country>(entity =>
        {
            entity.HasKey(e => e.CountryId).HasName("PK__Countrie__10D1609FE5FEC5C0");

            entity.ToTable("Countries", "HRM");

            entity.Property(e => e.CountryId).ValueGeneratedNever();
            entity.Property(e => e.CountryName).HasMaxLength(1000);
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.ToTable("Customers", "HRM");

            entity.Property(e => e.CustomerId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.CustomerCode).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Person).WithMany(p => p.Customers)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_Customers_Persons");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.ToTable("Departments", "INV");

            entity.Property(e => e.DepartmentId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.DepartmentName).HasMaxLength(1000);
            entity.Property(e => e.DepartmentSlug).HasMaxLength(500);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId).HasName("PK__Employee__7AD04F11C218845C");

            entity.ToTable("Employee", "HRM");

            entity.Property(e => e.EmployeeId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("date");
            entity.Property(e => e.EmployeeCode).HasMaxLength(50);

            entity.HasOne(d => d.Department).WithMany(p => p.Employees)
                .HasForeignKey(d => d.DepartmentId)
                .HasConstraintName("FK_Employee_EmployeeDepartments");

            entity.HasOne(d => d.Designation).WithMany(p => p.Employees)
                .HasForeignKey(d => d.DesignationId)
                .HasConstraintName("FK_Employee_EmployeeDesignation");

            entity.HasOne(d => d.Person).WithMany(p => p.Employees)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_Employee_Persons");
        });

        modelBuilder.Entity<EmployeeDepartment>(entity =>
        {
            entity.ToTable("EmployeeDepartments", "HRM");

            entity.Property(e => e.EmployeeDepartmentId).ValueGeneratedNever();
            entity.Property(e => e.Title).HasMaxLength(500);
        });

        modelBuilder.Entity<EmployeeDesignation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC07D5D46053");

            entity.ToTable("EmployeeDesignation", "HRM");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Title).HasMaxLength(50);
        });

        modelBuilder.Entity<ErpPermission>(entity =>
        {
            entity.HasKey(e => e.PermissionId).HasName("PK__ErpPermi__EFA6FB2FEE76B178");

            entity.ToTable("ErpPermissions", "SYSTEM");

            entity.Property(e => e.PermissionId).ValueGeneratedNever();

            entity.HasOne(d => d.UrlMenu).WithMany(p => p.ErpPermissions)
                .HasForeignKey(d => d.UrlMenuId)
                .HasConstraintName("FK__ErpPermis__UrlMe__37703C52");

            entity.HasOne(d => d.User).WithMany(p => p.ErpPermissions)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__ErpPermis__UserI__3864608B");
        });

        modelBuilder.Entity<FileManager>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FileMana__3214EC078B0E1999");

            entity.ToTable("FileManager", "MEDIA");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Caption).HasMaxLength(1000);
            entity.Property(e => e.Url)
                .HasMaxLength(1000)
                .HasColumnName("URL");

            entity.HasOne(d => d.Content).WithMany(p => p.FileManagers)
                .HasForeignKey(d => d.ContentId)
                .HasConstraintName("FK_FileManager_Content");
        });

        modelBuilder.Entity<FiscalPeriod>(entity =>
        {
            entity.HasKey(e => e.FiscalPeriodId).HasName("PK__FiscalPe__9E68FFEBBF5B3FA0");

            entity.ToTable("FiscalPeriods", "Accounting");

            entity.Property(e => e.FiscalPeriodId).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.EndDate).HasColumnType("date");
            entity.Property(e => e.IsClosed).HasDefaultValue(false);
            entity.Property(e => e.PeriodName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.StartDate).HasColumnType("date");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.FiscalPeriods)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK__FiscalPer__Creat__4A6E022D");
        });

        modelBuilder.Entity<Floor>(entity =>
        {
            entity.ToTable("Floors", "AST");

            entity.Property(e => e.FloorId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.FloorName).HasMaxLength(500);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Building).WithMany(p => p.Floors)
                .HasForeignKey(d => d.BuildingId)
                .HasConstraintName("FK_Floors_Buildings");
        });

        modelBuilder.Entity<InvoiceDetail>(entity =>
        {
            entity.HasKey(e => e.InvoiceDetailId).HasName("PK__InvoiceD__1F15781148657E0E");

            entity.ToTable("InvoiceDetail", "INV");

            entity.HasIndex(e => e.ProductId, "IX_InvoiceDetail_ProductId");

            entity.HasIndex(e => e.VariantId, "IX_InvoiceDetail_VariantId");

            entity.Property(e => e.InvoiceDetailId).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Discount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LineTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LineTotalWithTax).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Quantity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Remarks).HasMaxLength(500);
            entity.Property(e => e.TaxAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TaxRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.InvoiceMaster).WithMany(p => p.InvoiceDetails)
                .HasForeignKey(d => d.InvoiceMasterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InvoiceDetail_InvoiceMaster");

            entity.HasOne(d => d.Product).WithMany(p => p.InvoiceDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InvoiceDetail_Product");

            entity.HasOne(d => d.Variant).WithMany(p => p.InvoiceDetails)
                .HasForeignKey(d => d.VariantId)
                .HasConstraintName("FK_InvoiceDetail_Variant");
        });

        modelBuilder.Entity<InvoiceMaster>(entity =>
        {
            entity.HasKey(e => e.InvoiceMasterId).HasName("PK__InvoiceM__FD3450D199F346FC");

            entity.ToTable("InvoiceMaster", "INV");

            entity.HasIndex(e => e.CustomerId, "IX_InvoiceMaster_CustomerId");

            entity.HasIndex(e => e.InvoiceDate, "IX_InvoiceMaster_Date");

            entity.HasIndex(e => e.EmployeeId, "IX_InvoiceMaster_EmployeeId");

            entity.HasIndex(e => e.InvoiceNo, "UQ__InvoiceM__D796B2274B25F659").IsUnique();

            entity.Property(e => e.InvoiceMasterId).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CustomerRemarks).HasMaxLength(500);
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DueDate).HasColumnType("date");
            entity.Property(e => e.GrandTotal)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.InvoiceDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.InvoiceNo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.OfficeRemarks).HasMaxLength(500);
            entity.Property(e => e.TaxAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAmount)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Customer).WithMany(p => p.InvoiceMasters)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_InvoiceMaster_Customer");

            entity.HasOne(d => d.Employee).WithMany(p => p.InvoiceMasters)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("FK_InvoiceMaster_Employee");

            entity.HasOne(d => d.InvoiceSource).WithMany(p => p.InvoiceMasters)
                .HasForeignKey(d => d.InvoiceSourceId)
                .HasConstraintName("FK_InvoiceMaster_InvoiceSources");

            entity.HasOne(d => d.OrderStatus).WithMany(p => p.InvoiceMasters)
                .HasForeignKey(d => d.OrderStatusId)
                .HasConstraintName("FK_InvoiceMaster_OrderStatus");

            entity.HasOne(d => d.ParentInvoice).WithMany(p => p.InverseParentInvoice)
                .HasForeignKey(d => d.ParentInvoiceId)
                .HasConstraintName("FK_InvoiceMaster_InvoiceMaster");

            entity.HasOne(d => d.PaymentMethod).WithMany(p => p.InvoiceMasters)
                .HasForeignKey(d => d.PaymentMethodId)
                .HasConstraintName("FK_InvoiceMaster_PaymentMethod");

            entity.HasOne(d => d.PaymentStatus).WithMany(p => p.InvoiceMasters)
                .HasForeignKey(d => d.PaymentStatusId)
                .HasConstraintName("FK_InvoiceMaster_PaymentStatus");

            entity.HasOne(d => d.ServingTable).WithMany(p => p.InvoiceMasters)
                .HasForeignKey(d => d.ServingTableId)
                .HasConstraintName("FK_InvoiceMaster_ServingTable");

            entity.HasOne(d => d.ShippingType).WithMany(p => p.InvoiceMasters)
                .HasForeignKey(d => d.ShippingTypeId)
                .HasConstraintName("FK_InvoiceMaster_ShippingType");
        });

        modelBuilder.Entity<InvoiceSource>(entity =>
        {
            entity.HasKey(e => e.InvoiceSourceId).HasName("PK__InvoiceS__F401E9D338EDE6C9");

            entity.ToTable("InvoiceSources", "INV");

            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.SourceName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<JournalEntry>(entity =>
        {
            entity.HasKey(e => e.JournalEntryId).HasName("PK__JournalE__575A70DBB8A729C3");

            entity.ToTable("JournalEntries", "Accounting");

            entity.HasIndex(e => e.BranchId, "IX_JournalEntries_BranchId");

            entity.HasIndex(e => e.EntryDate, "IX_JournalEntries_EntryDate");

            entity.HasIndex(e => e.EntryNumber, "UQ__JournalE__488B566FA9420781").IsUnique();

            entity.Property(e => e.JournalEntryId).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.EntryDate).HasColumnType("date");
            entity.Property(e => e.EntryNumber)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ReferenceNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SourceModule)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Posted");
            entity.Property(e => e.TotalCredit)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalDebit)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.JournalEntryCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK__JournalEn__Creat__2630A1B7");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.JournalEntryUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .HasConstraintName("FK__JournalEn__Updat__2724C5F0");
        });

        modelBuilder.Entity<JournalLine>(entity =>
        {
            entity.HasKey(e => e.JournalLineId).HasName("PK__JournalL__C4D84425A24B4A1A");

            entity.ToTable("JournalLines", "Accounting");

            entity.Property(e => e.JournalLineId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Credit)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Debit)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.ReferenceType)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Coa).WithMany(p => p.JournalLines)
                .HasForeignKey(d => d.CoaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__JournalLi__CoaId__2EC5E7B8");

            entity.HasOne(d => d.JournalEntry).WithMany(p => p.JournalLines)
                .HasForeignKey(d => d.JournalEntryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__JournalLi__Journ__2DD1C37F");
        });

        modelBuilder.Entity<LaneAddress>(entity =>
        {
            entity.HasKey(e => e.AddressId).HasName("PK__LaneAddr__091C2AFB0350FDCB");

            entity.ToTable("LaneAddresses", "HRM");

            entity.Property(e => e.AddressId).ValueGeneratedNever();
            entity.Property(e => e.AddressType).HasMaxLength(500);
            entity.Property(e => e.Area).HasMaxLength(2000);
            entity.Property(e => e.FamousPlace).HasMaxLength(2000);
            entity.Property(e => e.LaneAddressOne).HasMaxLength(2000);
            entity.Property(e => e.LaneAddressTwo).HasMaxLength(2000);

            entity.HasOne(d => d.City).WithMany(p => p.LaneAddresses)
                .HasForeignKey(d => d.CityId)
                .HasConstraintName("FK_LaneAddresses_Cities1");

            entity.HasOne(d => d.Person).WithMany(p => p.LaneAddresses)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_LaneAddresses_Persons");
        });

        modelBuilder.Entity<LinkedContentItem>(entity =>
        {
            entity.HasKey(e => e.LinkedItemId).HasName("PK__LinkedCo__6F9EA4BA4F9AEC90");

            entity.ToTable("LinkedContentItems", "WEBCMS");

            entity.Property(e => e.LinkedItemId).ValueGeneratedNever();

            entity.HasOne(d => d.Content).WithMany(p => p.LinkedContentItemContents)
                .HasForeignKey(d => d.ContentId)
                .HasConstraintName("FK__LinkedCon__Conte__43D61337");

            entity.HasOne(d => d.LinkedContent).WithMany(p => p.LinkedContentItemLinkedContents)
                .HasForeignKey(d => d.LinkedContentId)
                .HasConstraintName("FK__LinkedCon__Linke__44CA3770");
        });

        modelBuilder.Entity<LoginHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LoginHis__3214EC079BF58EC4");

            entity.ToTable("LoginHistory", "HRM");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.LastLogin).HasColumnType("datetime");

            entity.HasOne(d => d.LoginUser).WithMany(p => p.LoginHistories)
                .HasForeignKey(d => d.LoginUserId)
                .HasConstraintName("FK_LoginHistory_LoginUsers");
        });

        modelBuilder.Entity<LoginUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LoginUse__3214EC076C4E1330");

            entity.ToTable("LoginUsers", "HRM");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Password).HasMaxLength(1000);
            entity.Property(e => e.UserName).HasMaxLength(50);

            entity.HasOne(d => d.Person).WithMany(p => p.LoginUsers)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_LoginUsers_Persons");

            entity.HasOne(d => d.Settings).WithMany(p => p.LoginUsers)
                .HasForeignKey(d => d.SettingsId)
                .HasConstraintName("FK_LoginUsers_Settings");
        });

        modelBuilder.Entity<LoginUserDeviceDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LoginUse__3214EC07E48F7649");

            entity.ToTable("LoginUserDeviceDetail", "HRM");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.DeviceIp)
                .HasMaxLength(100)
                .HasColumnName("DeviceIP");
            entity.Property(e => e.DeviceName).HasMaxLength(100);

            entity.HasOne(d => d.LoginUser).WithMany(p => p.LoginUserDeviceDetails)
                .HasForeignKey(d => d.LoginUserId)
                .HasConstraintName("FK_LoginUserDeviceDetail_LoginUsers");
        });

        modelBuilder.Entity<Material>(entity =>
        {
            entity.ToTable("Material", "INV");

            entity.Property(e => e.MaterialId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.MaterialName).HasMaxLength(500);
            entity.Property(e => e.MaterialSlug).HasMaxLength(500);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Notifica__3214EC07C4159632");

            entity.ToTable("Notifications", "SYSTEM");

            entity.HasIndex(e => e.GroupName, "IX_Notifications_GroupName");

            entity.HasIndex(e => new { e.GroupName, e.IsRead }, "IX_Notifications_GroupName_IsRead");

            entity.HasIndex(e => e.UserId, "IX_Notifications_UserId");

            entity.HasIndex(e => new { e.UserId, e.IsRead }, "IX_Notifications_UserId_IsRead");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.GroupName).HasMaxLength(255);
            entity.Property(e => e.Message).IsRequired();

            entity.HasOne(d => d.NotificationType).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.NotificationTypeId)
                .HasConstraintName("FK_Notifications_NotificationTypes");
        });

        modelBuilder.Entity<NotificationType>(entity =>
        {
            entity.ToTable("NotificationTypes", "SYSTEM");

            entity.Property(e => e.NotificationTypeId).ValueGeneratedNever();
            entity.Property(e => e.NotificationTypeName).HasMaxLength(500);
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.ToTable("OrderDetail", "INV");

            entity.Property(e => e.OrderDetailId).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Discount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LineTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LineTotalWithTax).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Quantity).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Remarks).HasMaxLength(500);
            entity.Property(e => e.TaxAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TaxRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.OrderMaster).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.OrderMasterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderDetail_OrderMaster");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderDetail_Product");

            entity.HasOne(d => d.Variant).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.VariantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderDetail_ProductVariant");
        });

        modelBuilder.Entity<OrderMaster>(entity =>
        {
            entity.HasKey(e => e.OrderMasterId).HasName("PK__OrderMas__4DCAA5B2A297F67C");

            entity.ToTable("OrderMaster", "INV");

            entity.Property(e => e.OrderMasterId).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CustomerRemarks).HasMaxLength(500);
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.GrandTotal)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.OfficeRemarks).HasMaxLength(500);
            entity.Property(e => e.OrderDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.OrderNo).HasMaxLength(50);
            entity.Property(e => e.OrderStatusId).HasDefaultValue(1);
            entity.Property(e => e.TaxAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAmount)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Customer).WithMany(p => p.OrderMasters)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_OrderMaster_Customers");

            entity.HasOne(d => d.Employee).WithMany(p => p.OrderMasters)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("FK_OrderMaster_Employee");

            entity.HasOne(d => d.OrderSource).WithMany(p => p.OrderMasters)
                .HasForeignKey(d => d.OrderSourceId)
                .HasConstraintName("FK_OrderMaster_InvoiceSources");

            entity.HasOne(d => d.OrderStatus).WithMany(p => p.OrderMasters)
                .HasForeignKey(d => d.OrderStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderMaster_OrderStatus");

            entity.HasOne(d => d.ParentOrder).WithMany(p => p.InverseParentOrder)
                .HasForeignKey(d => d.ParentOrderId)
                .HasConstraintName("FK_OrderMaster_Parent");

            entity.HasOne(d => d.PaymentMethod).WithMany(p => p.OrderMasters)
                .HasForeignKey(d => d.PaymentMethodId)
                .HasConstraintName("FK_OrderMaster_PaymentMethods");

            entity.HasOne(d => d.PaymentStatus).WithMany(p => p.OrderMasters)
                .HasForeignKey(d => d.PaymentStatusId)
                .HasConstraintName("FK_OrderMaster_PaymentStatus");

            entity.HasOne(d => d.ServingTable).WithMany(p => p.OrderMasters)
                .HasForeignKey(d => d.ServingTableId)
                .HasConstraintName("FK_OrderMaster_ServingTable");

            entity.HasOne(d => d.ShippingType).WithMany(p => p.OrderMasters)
                .HasForeignKey(d => d.ShippingTypeId)
                .HasConstraintName("FK_OrderMaster_ShippingType");
        });

        modelBuilder.Entity<OrderStatus>(entity =>
        {
            entity.HasKey(e => e.OrderStatusId).HasName("PK__OrderSta__BC674CA1280924C9");

            entity.ToTable("OrderStatus", "INV");

            entity.Property(e => e.OrderStatusName)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<Organization>(entity =>
        {
            entity.HasKey(e => e.OrganizationId).HasName("PK__Business__A1682FC590D5A421");

            entity.ToTable("Organizations", "Business");

            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.OrganizationName).HasMaxLength(500);
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payments__9B556A38A491B0AD");

            entity.ToTable("Payments", "Accounting");

            entity.Property(e => e.PaymentId).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PaymentDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("date");
            entity.Property(e => e.PaymentMode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PaymentType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.SourceType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.JournalEntry).WithMany(p => p.Payments)
                .HasForeignKey(d => d.JournalEntryId)
                .HasConstraintName("FK__Payments__Journa__45A94D10");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.ToTable("PaymentMethods", "Setup");

            entity.Property(e => e.PaymentMethodId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("date");
            entity.Property(e => e.Name).HasMaxLength(50);
        });

        modelBuilder.Entity<PaymentStatus>(entity =>
        {
            entity.HasKey(e => e.PaymentStatusId).HasName("PK__PaymentS__34F8AC3FD3FD306B");

            entity.ToTable("PaymentStatus", "Setup");

            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Person>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Persons__3214EC0730ACEE27");

            entity.ToTable("Persons", "HRM");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Cnic)
                .HasMaxLength(50)
                .HasColumnName("CNIC");
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(50);
            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.ImageUrl).HasColumnName("ImageURL");
            entity.Property(e => e.LastName).HasMaxLength(50);
            entity.Property(e => e.MobileNumber).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.SocialSecurity).HasMaxLength(10);

            entity.HasOne(d => d.Branch).WithMany(p => p.People)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("FK_Persons_Branches");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("Products", "INV");

            entity.Property(e => e.ProductId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.ProductName).HasMaxLength(1000);
            entity.Property(e => e.ProductSlug).HasMaxLength(500);
            entity.Property(e => e.Qoh)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("QOH");
            entity.Property(e => e.Uomid).HasColumnName("UOMId");

            entity.HasOne(d => d.Brand).WithMany(p => p.Products)
                .HasForeignKey(d => d.BrandId)
                .HasConstraintName("FK_Products_Brands");

            entity.HasOne(d => d.BrandModel).WithMany(p => p.Products)
                .HasForeignKey(d => d.BrandModelId)
                .HasConstraintName("FK_Products_BrandModels");

            entity.HasOne(d => d.Organization).WithMany(p => p.Products)
                .HasForeignKey(d => d.OrganizationId)
                .HasConstraintName("FK_Products_Organizations");

            entity.HasOne(d => d.SubCategory).WithMany(p => p.Products)
                .HasForeignKey(d => d.SubCategoryId)
                .HasConstraintName("FK_Products_SubCategoryId");

            entity.HasOne(d => d.Supplier).WithMany(p => p.Products)
                .HasForeignKey(d => d.SupplierId)
                .HasConstraintName("FK_Products_Supplier");

            entity.HasOne(d => d.Uom).WithMany(p => p.Products)
                .HasForeignKey(d => d.Uomid)
                .HasConstraintName("FK_Products_UOM");
        });

        modelBuilder.Entity<ProductBranch>(entity =>
        {
            entity.HasKey(e => e.ProductBranchesId);

            entity.ToTable("ProductBranches", "INV");

            entity.Property(e => e.ProductBranchesId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Branch).WithMany(p => p.ProductBranches)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("FK_ProductBranches_Branches");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductBranches)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_ProductBranches_Products");
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.ToTable("ProductImages", "INV");

            entity.Property(e => e.ProductImageId).ValueGeneratedNever();
            entity.Property(e => e.Caption).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasMaxLength(1000);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductImages)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_ProductImages_Products");
        });

        modelBuilder.Entity<ProductVariant>(entity =>
        {
            entity.HasKey(e => e.VariantId);

            entity.ToTable("ProductVariants", "INV");

            entity.Property(e => e.VariantId).ValueGeneratedNever();
            entity.Property(e => e.BarCode).HasMaxLength(500);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.LastPurchase).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.QuantityPerUnit).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.SubUomid).HasColumnName("SubUOMId");

            entity.HasOne(d => d.Color).WithMany(p => p.ProductVariants)
                .HasForeignKey(d => d.ColorId)
                .HasConstraintName("FK_ProductVariants_Colors");

            entity.HasOne(d => d.Material).WithMany(p => p.ProductVariants)
                .HasForeignKey(d => d.MaterialId)
                .HasConstraintName("FK_ProductVariants_Material");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductVariants)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_ProductVariants_Products");

            entity.HasOne(d => d.Size).WithMany(p => p.ProductVariants)
                .HasForeignKey(d => d.SizeId)
                .HasConstraintName("FK_ProductVariants_Sizes");

            entity.HasOne(d => d.SubUom).WithMany(p => p.ProductVariants)
                .HasForeignKey(d => d.SubUomid)
                .HasConstraintName("FK_ProductVariants_UOMSub1");

            entity.HasOne(d => d.TaxSlab).WithMany(p => p.ProductVariants)
                .HasForeignKey(d => d.TaxSlabId)
                .HasConstraintName("FK_ProductVariants_TaxSlabs");
        });

        modelBuilder.Entity<PurchaseDetail>(entity =>
        {
            entity.ToTable("PurchaseDetail", "INV");

            entity.Property(e => e.PurchaseDetailId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.DiscountAmount)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LineTotal)
                .HasComputedColumnSql("([Qty]*[UnitPrice]-[DiscountAmount])", true)
                .HasColumnType("decimal(38, 4)");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Qty).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalPrice)
                .HasComputedColumnSql("([Qty]*[UnitPrice])", true)
                .HasColumnType("decimal(37, 4)");
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.PurchaseMaster).WithMany(p => p.PurchaseDetails)
                .HasForeignKey(d => d.PurchaseMasterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PurchaseD__Purch__15DA3E5D");

            entity.HasOne(d => d.Variant).WithMany(p => p.PurchaseDetails)
                .HasForeignKey(d => d.VariantId)
                .HasConstraintName("FK__PurchaseD__Varia__16CE6296");
        });

        modelBuilder.Entity<PurchaseMaster>(entity =>
        {
            entity.HasKey(e => e.PurchaseMasterId).HasName("PK__Purchase__5450C11901866B34");

            entity.ToTable("PurchaseMaster", "INV");

            entity.HasIndex(e => e.PurchaseNumber, "UQ__Purchase__373B5B6EE9029448").IsUnique();

            entity.Property(e => e.PurchaseMasterId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.DiscountAmount)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.GrandTotal)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.PurchaseDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PurchaseNumber).HasMaxLength(50);
            entity.Property(e => e.PurchaseType).HasDefaultValue(1);
            entity.Property(e => e.Remarks).HasMaxLength(500);
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.TaxAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalAmount)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Supplier).WithMany(p => p.PurchaseMasters)
                .HasForeignKey(d => d.SupplierId)
                .HasConstraintName("FK_PurchaseMaster_Supplier");
        });

        modelBuilder.Entity<ReconciliationLog>(entity =>
        {
            entity.HasKey(e => e.ReconciliationId).HasName("PK__Reconcil__096DC80051808EBD");

            entity.ToTable("ReconciliationLogs", "Accounting");

            entity.Property(e => e.ReconciliationId).ValueGeneratedNever();
            entity.Property(e => e.AdjustmentAmount)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.SourceType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__Reviews__74BC79CEDF63D3BA");

            entity.ToTable("Reviews", "WEBCMS");

            entity.Property(e => e.ReviewId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ReviewComment).HasMaxLength(1000);
            entity.Property(e => e.UserBrowser).HasMaxLength(50);
            entity.Property(e => e.UserIp)
                .HasMaxLength(50)
                .HasColumnName("UserIP");

            entity.HasOne(d => d.Content).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.ContentId)
                .HasConstraintName("FK__Reviews__Content__45BE5BA9");

            entity.HasOne(d => d.LoginUser).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.LoginUserId)
                .HasConstraintName("FK__Reviews__LoginUs__46B27FE2");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC07BCE7C156");

            entity.ToTable("Roles", "SYSTEM");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(50);
        });

        modelBuilder.Entity<ServingTable>(entity =>
        {
            entity.ToTable("ServingTables", "AST");

            entity.Property(e => e.ServingTableId).ValueGeneratedNever();
            entity.Property(e => e.TableName).HasMaxLength(50);

            entity.HasOne(d => d.Floor).WithMany(p => p.ServingTables)
                .HasForeignKey(d => d.FloorId)
                .HasConstraintName("FK_ServingTables_Floors");
        });

        modelBuilder.Entity<Setting>(entity =>
        {
            entity.HasKey(e => e.SettingsId).HasName("PK__Settings__991B19FC516B0BB6");

            entity.ToTable("Settings", "SYSTEM");

            entity.Property(e => e.SettingsId).ValueGeneratedNever();
            entity.Property(e => e.ApplicationName).HasMaxLength(1000);
            entity.Property(e => e.ApplicationUrl)
                .HasMaxLength(1000)
                .HasColumnName("ApplicationURL");
        });

        modelBuilder.Entity<ShippingType>(entity =>
        {
            entity.HasKey(e => e.ShippingTypeId).HasName("PK__Shipping__46789510DDA272C3");

            entity.ToTable("ShippingType", "Setup");

            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Size>(entity =>
        {
            entity.ToTable("Sizes", "INV");

            entity.Property(e => e.SizeId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.SizeName).HasMaxLength(1000);
            entity.Property(e => e.SizeSlug).HasMaxLength(100);
        });

        modelBuilder.Entity<StateProvince>(entity =>
        {
            entity.HasKey(e => e.StateProvinceId).HasName("PK__StatePro__9122A951D4833E19");

            entity.ToTable("StateProvince", "HRM");

            entity.Property(e => e.StateProvinceId).ValueGeneratedNever();
            entity.Property(e => e.StateProvinceName).HasMaxLength(1000);

            entity.HasOne(d => d.Country).WithMany(p => p.StateProvinces)
                .HasForeignKey(d => d.CountryId)
                .HasConstraintName("FK_StateProvince_Countries");
        });

        modelBuilder.Entity<SubCategory>(entity =>
        {
            entity.HasKey(e => e.SubCategoryId).HasName("PK_SubCategoryId");

            entity.ToTable("SubCategory", "INV");

            entity.Property(e => e.SubCategoryId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.HarmonizedSystemCode).HasMaxLength(500);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.SubCategoryName).HasMaxLength(1000);
            entity.Property(e => e.SubCategorySlug).HasMaxLength(500);

            entity.HasOne(d => d.Category).WithMany(p => p.SubCategories)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_SubCategoryId_Categories");
        });

        modelBuilder.Entity<Supplier>(entity =>
        {
            entity.HasKey(e => e.SupplierId).HasName("PK__Supplier__4BE666B48F48E7DA");

            entity.ToTable("Supplier", "HRM");

            entity.Property(e => e.SupplierId).ValueGeneratedNever();
            entity.Property(e => e.CompanyLogo).HasMaxLength(500);
            entity.Property(e => e.CreatedOn).HasColumnType("date");
            entity.Property(e => e.Ntn)
                .HasMaxLength(100)
                .HasColumnName("NTN");
            entity.Property(e => e.SupplierBusinessName).HasMaxLength(500);
            entity.Property(e => e.SupplierCode).HasMaxLength(500);
        });

        modelBuilder.Entity<SupplierContact>(entity =>
        {
            entity.HasKey(e => e.SpplierContactId);

            entity.ToTable("SupplierContact", "HRM");

            entity.Property(e => e.SpplierContactId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Person).WithMany(p => p.SupplierContacts)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_SupplierContact_Persons");

            entity.HasOne(d => d.Supplier).WithMany(p => p.SupplierContacts)
                .HasForeignKey(d => d.SupplierId)
                .HasConstraintName("FK_SupplierContact_Supplier");
        });

        modelBuilder.Entity<SystemPreference>(entity =>
        {
            entity.HasKey(e => e.SystemPreferenceId).HasName("PK_SystemPreferences_Id");

            entity.ToTable("SystemPreferences", "Setup");

            entity.Property(e => e.SystemPreferenceId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.BackupLocation).HasMaxLength(500);
            entity.Property(e => e.CompanyLogoUrl).HasMaxLength(500);
            entity.Property(e => e.CompanyName).HasMaxLength(200);
            entity.Property(e => e.CurrencyCode).HasMaxLength(10);
            entity.Property(e => e.CurrencySymbol).HasMaxLength(10);
            entity.Property(e => e.DateFormat).HasMaxLength(20);
            entity.Property(e => e.DecimalPlaces).HasDefaultValue(2);
            entity.Property(e => e.DefaultFromEmail).HasMaxLength(200);
            entity.Property(e => e.DefaultLanguage).HasMaxLength(50);
            entity.Property(e => e.DefaultTaxRate).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.DefaultWarehouse).HasMaxLength(100);
            entity.Property(e => e.InvoicePrefix).HasMaxLength(20);
            entity.Property(e => e.QuotationPrefix).HasMaxLength(20);
            entity.Property(e => e.ReceiptPrefix).HasMaxLength(20);
            entity.Property(e => e.SmtpPassword).HasMaxLength(200);
            entity.Property(e => e.SmtpServer).HasMaxLength(200);
            entity.Property(e => e.SmtpUserName).HasMaxLength(200);
            entity.Property(e => e.TaxRegistrationNumber).HasMaxLength(100);
            entity.Property(e => e.TimeZone).HasMaxLength(100);

            entity.HasOne(d => d.Branch).WithMany(p => p.SystemPreferences)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SystemPreferences_Branch");
        });

        modelBuilder.Entity<TaxSlab>(entity =>
        {
            entity.HasKey(e => e.TaxSlabId).HasName("PK__TaxSlabs__4DA9C7B314BCC7A6");

            entity.ToTable("TaxSlabs", "SYSTEM");

            entity.Property(e => e.TaxSlabId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Rate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.SlabName)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<TaxTransaction>(entity =>
        {
            entity.HasKey(e => e.TaxTransactionId).HasName("PK__TaxTrans__D3DE177AC392AC1A");

            entity.ToTable("TaxTransactions", "Accounting");

            entity.Property(e => e.TaxTransactionId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.BaseAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SourceType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TaxAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TaxRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.TaxType)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.JournalEntry).WithMany(p => p.TaxTransactions)
                .HasForeignKey(d => d.JournalEntryId)
                .HasConstraintName("FK__TaxTransa__Journ__5026DB83");

            entity.HasOne(d => d.TaxAccount).WithMany(p => p.TaxTransactions)
                .HasForeignKey(d => d.TaxAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TaxTransa__TaxAc__4F32B74A");
        });

        modelBuilder.Entity<Uom>(entity =>
        {
            entity.ToTable("UOM", "INV");

            entity.Property(e => e.Uomid)
                .ValueGeneratedNever()
                .HasColumnName("UOMId");
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Uomname)
                .HasMaxLength(50)
                .HasColumnName("UOMName");
            entity.Property(e => e.Uomtype)
                .HasMaxLength(50)
                .HasColumnName("UOMType");
        });

        modelBuilder.Entity<Uomsub>(entity =>
        {
            entity.HasKey(e => e.SubUomid);

            entity.ToTable("UOMSub", "INV");

            entity.Property(e => e.SubUomid)
                .ValueGeneratedNever()
                .HasColumnName("SubUOMId");
            entity.Property(e => e.ConversionFactor).HasColumnType("decimal(4, 2)");
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.SubUomname)
                .HasMaxLength(500)
                .HasColumnName("SubUOMName");
            entity.Property(e => e.Uomid).HasColumnName("UOMId");

            entity.HasOne(d => d.Uom).WithMany(p => p.Uomsubs)
                .HasForeignKey(d => d.Uomid)
                .HasConstraintName("FK_UOMSub_UOM");
        });

        modelBuilder.Entity<UrlMenu>(entity =>
        {
            entity.HasKey(e => e.UrlMenuId).HasName("PK__UrlMenu__1E1429F7BC8DD63A");

            entity.ToTable("UrlMenu", "SYSTEM");

            entity.Property(e => e.UrlMenuId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.UrlMenuLink).HasMaxLength(50);
        });

        modelBuilder.Entity<UserAssignedBranch>(entity =>
        {
            entity.HasKey(e => e.UserAssignedBranches);

            entity.ToTable("UserAssignedBranches", "HRM");

            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Branch).WithMany(p => p.UserAssignedBranches)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("FK_UserAssignedBranches_Branches");

            entity.HasOne(d => d.LoginUser).WithMany(p => p.UserAssignedBranches)
                .HasForeignKey(d => d.LoginUserId)
                .HasConstraintName("FK_UserAssignedBranches_LoginUsers");
        });

        modelBuilder.Entity<Website>(entity =>
        {
            entity.HasKey(e => e.WebsiteId).HasName("PK__Website__3F146DA9C3C22F69");

            entity.ToTable("Website", "SYSTEM");

            entity.Property(e => e.WebsiteId).ValueGeneratedNever();
            entity.Property(e => e.SupportEmail).HasMaxLength(255);
            entity.Property(e => e.WebsiteName).HasMaxLength(500);
        });

        modelBuilder.Entity<WebsiteDatum>(entity =>
        {
            entity.HasKey(e => e.WebsiteDataId).HasName("PK__WebsiteD__E06C88F0846D487E");

            entity.ToTable("WebsiteData", "SYSTEM");

            entity.Property(e => e.WebsiteDataId).ValueGeneratedNever();
            entity.Property(e => e.Title).HasMaxLength(50);
            entity.Property(e => e.Value)
                .HasMaxLength(50)
                .HasColumnName("value");

            entity.HasOne(d => d.Website).WithMany(p => p.WebsiteData)
                .HasForeignKey(d => d.WebsiteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__WebsiteDa__Websi__395884C4");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}