// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MainModels.Models;

public partial class OneDb : DbContext
{
    public OneDb(DbContextOptions<OneDb> options)
        : base(options)
    {
    }

    public virtual DbSet<AssignedRole> AssignedRoles { get; set; }

    public virtual DbSet<Branch> Branches { get; set; }

    public virtual DbSet<Brand> Brands { get; set; }

    public virtual DbSet<BusinessCategory> BusinessCategories { get; set; }

    public virtual DbSet<BusinessEntityType> BusinessEntityTypes { get; set; }

    public virtual DbSet<BusinessStoreType> BusinessStoreTypes { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<CmsContentSharedCategory> CmsContentSharedCategories { get; set; }

    public virtual DbSet<CmsEmail> CmsEmails { get; set; }

    public virtual DbSet<CmsemailSent> CmsemailSents { get; set; }

    public virtual DbSet<Color> Colors { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<Content> Contents { get; set; }

    public virtual DbSet<ContentCategory> ContentCategories { get; set; }

    public virtual DbSet<ContentType> ContentTypes { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Department1> Departments1 { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<EmployeeDesignation> EmployeeDesignations { get; set; }

    public virtual DbSet<ErpPermission> ErpPermissions { get; set; }

    public virtual DbSet<FileManager> FileManagers { get; set; }

    public virtual DbSet<LaneAddress> LaneAddresses { get; set; }

    public virtual DbSet<LinkedContentItem> LinkedContentItems { get; set; }

    public virtual DbSet<LoginHistory> LoginHistories { get; set; }

    public virtual DbSet<LoginUser> LoginUsers { get; set; }

    public virtual DbSet<LoginUserDeviceDetail> LoginUserDeviceDetails { get; set; }

    public virtual DbSet<Material> Materials { get; set; }

    public virtual DbSet<Organization> Organizations { get; set; }

    public virtual DbSet<Person> Persons { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductBranch> ProductBranches { get; set; }

    public virtual DbSet<ProductImage> ProductImages { get; set; }

    public virtual DbSet<ProductVariant> ProductVariants { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Setting> Settings { get; set; }

    public virtual DbSet<Size> Sizes { get; set; }

    public virtual DbSet<StateProvince> StateProvinces { get; set; }

    public virtual DbSet<SubCategory> SubCategories { get; set; }

    public virtual DbSet<Supplier> Suppliers { get; set; }

    public virtual DbSet<Uom> Uoms { get; set; }

    public virtual DbSet<Uomsub> Uomsubs { get; set; }

    public virtual DbSet<UrlMenu> UrlMenus { get; set; }

    public virtual DbSet<UserAssignedBranch> UserAssignedBranches { get; set; }

    public virtual DbSet<Website> Websites { get; set; }

    public virtual DbSet<WebsiteDatum> WebsiteData { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AssignedRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Assigned__3214EC07B88445F7");

            entity.ToTable("AssignedRoles", "SYSTEM");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Login).WithMany(p => p.AssignedRoles)
                .HasForeignKey(d => d.LoginId)
                .HasConstraintName("FK__AssignedR__Login__2CF2ADDF");

            entity.HasOne(d => d.Role).WithMany(p => p.AssignedRoles)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK__AssignedR__RoleI__2DE6D218");
        });

        modelBuilder.Entity<Branch>(entity =>
        {
            entity.ToTable("Branches", "Business");

            entity.Property(e => e.BranchId).ValueGeneratedNever();
            entity.Property(e => e.BranchCode)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.BranchName).HasMaxLength(500);

            entity.HasOne(d => d.BusinessCategory).WithMany(p => p.Branches)
                .HasForeignKey(d => d.BusinessCategoryId)
                .HasConstraintName("FK_Branches_BusinessCategory");

            entity.HasOne(d => d.BusinessCategoryNavigation).WithMany(p => p.Branches)
                .HasForeignKey(d => d.BusinessCategoryId)
                .HasConstraintName("FK_Branches_BusinessStoreType");

            entity.HasOne(d => d.BusinessEntityType).WithMany(p => p.Branches)
                .HasForeignKey(d => d.BusinessEntityTypeId)
                .HasConstraintName("FK_Branches_BusinessEntityType");

            entity.HasOne(d => d.Organization).WithMany(p => p.Branches)
                .HasForeignKey(d => d.OrganizationId)
                .HasConstraintName("FK_Branches_Organizations");
        });

        modelBuilder.Entity<Brand>(entity =>
        {
            entity.ToTable("Brands", "INV");

            entity.Property(e => e.BrandId).ValueGeneratedNever();
            entity.Property(e => e.BrandName).HasMaxLength(500);
            entity.Property(e => e.BrandSlug).HasMaxLength(500);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<BusinessCategory>(entity =>
        {
            entity.HasKey(e => e.BusinessCategoryId).HasName("PK__Business__4024A26DA2DD4A2E");

            entity.ToTable("BusinessCategory", "Business");

            entity.Property(e => e.BusinessCategoryId).ValueGeneratedNever();
            entity.Property(e => e.BusinessCategoryName).HasMaxLength(500);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<BusinessEntityType>(entity =>
        {
            entity.HasKey(e => e.BusinessEntityTypeId).HasName("PK__Business__837393DAFE0EAB5C");

            entity.ToTable("BusinessEntityType", "Business");

            entity.Property(e => e.BusinessEntityTypeId).ValueGeneratedNever();
            entity.Property(e => e.BusinessEntityTypeName).HasMaxLength(500);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<BusinessStoreType>(entity =>
        {
            entity.HasKey(e => e.BusinessStoreTypeId).HasName("PK__Business__673FC7EDA67B78A0");

            entity.ToTable("BusinessStoreType", "Business");

            entity.Property(e => e.BusinessStoreTypeId).ValueGeneratedNever();
            entity.Property(e => e.BusinessStoreTypeName).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.ToTable("Categories", "INV");

            entity.Property(e => e.CategoryId).ValueGeneratedNever();
            entity.Property(e => e.CategoryName).HasMaxLength(1000);
            entity.Property(e => e.CategorySlug).HasMaxLength(500);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Department).WithMany(p => p.Categories)
                .HasForeignKey(d => d.DepartmentId)
                .HasConstraintName("FK_Categories_Departments");
        });

        modelBuilder.Entity<City>(entity =>
        {
            entity.HasKey(e => e.CityId).HasName("PK__Cities__F2D21B76833C04B8");

            entity.ToTable("Cities", "HRM");

            entity.Property(e => e.CityId).ValueGeneratedNever();
            entity.Property(e => e.CityName).HasMaxLength(1000);

            entity.HasOne(d => d.StateProvince).WithMany(p => p.Cities)
                .HasForeignKey(d => d.StateProvinceId)
                .HasConstraintName("FK_Cities_StateProvince");
        });

        modelBuilder.Entity<CmsContentSharedCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CmsConte__3214EC07410C3E57");

            entity.ToTable("CmsContentSharedCategory", "WEBCMS");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Category).WithMany(p => p.CmsContentSharedCategories)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK__CmsConten__Categ__31B762FC");

            entity.HasOne(d => d.Content).WithMany(p => p.CmsContentSharedCategories)
                .HasForeignKey(d => d.ContentId)
                .HasConstraintName("FK__CmsConten__Conte__32AB8735");
        });

        modelBuilder.Entity<CmsEmail>(entity =>
        {
            entity.HasKey(e => e.EmailId).HasName("PK__CmsEmail__7ED91ACFB30893D6");

            entity.ToTable("CmsEmail", "WEBCMS");

            entity.Property(e => e.EmailId).ValueGeneratedNever();
            entity.Property(e => e.DateCreated).HasColumnType("date");
            entity.Property(e => e.EmailSender).HasMaxLength(500);
            entity.Property(e => e.EmailSubject).HasMaxLength(500);
            entity.Property(e => e.FirstName).HasMaxLength(500);
            entity.Property(e => e.FullName).HasMaxLength(500);
            entity.Property(e => e.LandLine).HasMaxLength(500);
            entity.Property(e => e.LastName).HasMaxLength(500);
            entity.Property(e => e.Mobile).HasMaxLength(500);
            entity.Property(e => e.StatusMessage).HasMaxLength(500);

            entity.HasOne(d => d.Website).WithMany(p => p.CmsEmails)
                .HasForeignKey(d => d.WebsiteId)
                .HasConstraintName("FK__CmsEmail__Websit__339FAB6E");
        });

        modelBuilder.Entity<CmsemailSent>(entity =>
        {
            entity.HasKey(e => e.EmailSentId).HasName("PK__CMSEmail__456E5F9B64349B9F");

            entity.ToTable("CMSEmailSent", "WEBCMS");

            entity.Property(e => e.EmailSentId).ValueGeneratedNever();
            entity.Property(e => e.Body).IsRequired();
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.FromEmailAddress)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.SentDateTime).HasColumnType("datetime");
            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.ToEmailAddress)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Email).WithMany(p => p.CmsemailSents)
                .HasForeignKey(d => d.EmailId)
                .HasConstraintName("FK__CMSEmailS__Email__3493CFA7");

            entity.HasOne(d => d.EmailNavigation).WithMany(p => p.CmsemailSents)
                .HasForeignKey(d => d.EmailId)
                .HasConstraintName("FK__CMSEmailS__Email__3587F3E0");
        });

        modelBuilder.Entity<Color>(entity =>
        {
            entity.ToTable("Colors", "INV");

            entity.Property(e => e.ColorId).ValueGeneratedNever();
            entity.Property(e => e.ColorName).HasMaxLength(500);
            entity.Property(e => e.ColorSlug).HasMaxLength(500);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<Comment>(entity =>
        {
            entity.HasKey(e => e.CommentId).HasName("PK__Comments__C3B4DFCA3C858BE9");

            entity.ToTable("Comments", "WEBCMS");

            entity.Property(e => e.CommentId).ValueGeneratedNever();
            entity.Property(e => e.Comment1)
                .HasMaxLength(1000)
                .HasColumnName("Comment");
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.UserBrowser).HasMaxLength(50);
            entity.Property(e => e.UserIp)
                .HasMaxLength(50)
                .HasColumnName("UserIP");

            entity.HasOne(d => d.Review).WithMany(p => p.Comments)
                .HasForeignKey(d => d.ReviewId)
                .HasConstraintName("FK__Comments__Review__367C1819");
        });

        modelBuilder.Entity<Content>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Content__3214EC0782619E9B");

            entity.ToTable("Content", "WEBCMS");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ContentSlug).HasMaxLength(1000);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Date).HasColumnType("date");
            entity.Property(e => e.FwdUrl).HasMaxLength(800);
            entity.Property(e => e.HeaderPhoto).HasMaxLength(500);
            entity.Property(e => e.Icon).HasMaxLength(50);
            entity.Property(e => e.ImageSource).HasMaxLength(500);
            entity.Property(e => e.Ipaddress).HasMaxLength(500);
            entity.Property(e => e.MetaDescription).HasMaxLength(1500);
            entity.Property(e => e.MetaKeyword).HasMaxLength(1500);
            entity.Property(e => e.MetaTitle).HasMaxLength(1500);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(1000);
            entity.Property(e => e.Note).HasMaxLength(1000);
            entity.Property(e => e.OtherTitle).HasMaxLength(1500);
            entity.Property(e => e.Tagline).HasMaxLength(1000);
            entity.Property(e => e.Thumbnail).HasMaxLength(500);
            entity.Property(e => e.VideoLink).HasMaxLength(500);

            entity.HasOne(d => d.ContentType).WithMany(p => p.Contents)
                .HasForeignKey(d => d.ContentTypeId)
                .HasConstraintName("FK__Content__Content__37703C52");

            entity.HasOne(d => d.LoginUser).WithMany(p => p.Contents)
                .HasForeignKey(d => d.LoginUserId)
                .HasConstraintName("FK__Content__LoginUs__3864608B");

            entity.HasOne(d => d.WebSite).WithMany(p => p.Contents)
                .HasForeignKey(d => d.WebSiteId)
                .HasConstraintName("FK__Content__WebSite__395884C4");
        });

        modelBuilder.Entity<ContentCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ContentC__3214EC0759B49D2B");

            entity.ToTable("ContentCategory", "WEBCMS");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasMaxLength(50);
            entity.Property(e => e.Name).HasMaxLength(501);
            entity.Property(e => e.Slug).HasMaxLength(501);

            entity.HasOne(d => d.Type).WithMany(p => p.ContentCategories)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContentCategory_ContentType");
        });

        modelBuilder.Entity<ContentType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ContentT__3214EC070F37F922");

            entity.ToTable("ContentType", "WEBCMS");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.TypeSlug).HasMaxLength(100);
        });

        modelBuilder.Entity<Country>(entity =>
        {
            entity.HasKey(e => e.CountryId).HasName("PK__Countrie__10D1609F325AFB00");

            entity.ToTable("Countries", "HRM");

            entity.Property(e => e.CountryId).ValueGeneratedNever();
            entity.Property(e => e.CountryName).HasMaxLength(1000);
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Departme__3214EC0759C53F2A");

            entity.ToTable("Department", "HRM");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Title).HasMaxLength(50);
        });

        modelBuilder.Entity<Department1>(entity =>
        {
            entity.HasKey(e => e.DepartmentId);

            entity.ToTable("Departments", "INV");

            entity.Property(e => e.DepartmentId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.DepartmentName).HasMaxLength(1000);
            entity.Property(e => e.DepartmentSlug).HasMaxLength(500);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId).HasName("PK__Employee__7AD04F11BD236721");

            entity.ToTable("Employee", "HRM");

            entity.Property(e => e.EmployeeId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("date");
            entity.Property(e => e.EmployeeCode).HasMaxLength(50);

            entity.HasOne(d => d.Department).WithMany(p => p.Employees)
                .HasForeignKey(d => d.DepartmentId)
                .HasConstraintName("FK_Employee_Department");

            entity.HasOne(d => d.Designation).WithMany(p => p.Employees)
                .HasForeignKey(d => d.DesignationId)
                .HasConstraintName("FK_Employee_EmployeeDesignation");

            entity.HasOne(d => d.Person).WithMany(p => p.Employees)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_Employee_Persons");
        });

        modelBuilder.Entity<EmployeeDesignation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC07DD9840AB");

            entity.ToTable("EmployeeDesignation", "HRM");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Title).HasMaxLength(50);
        });

        modelBuilder.Entity<ErpPermission>(entity =>
        {
            entity.HasKey(e => e.PermissionId).HasName("PK__ErpPermi__EFA6FB2FEC9E5A81");

            entity.ToTable("ErpPermissions", "SYSTEM");

            entity.Property(e => e.PermissionId).ValueGeneratedNever();

            entity.HasOne(d => d.UrlMenu).WithMany(p => p.ErpPermissions)
                .HasForeignKey(d => d.UrlMenuId)
                .HasConstraintName("FK__ErpPermis__UrlMe__2EDAF651");

            entity.HasOne(d => d.User).WithMany(p => p.ErpPermissions)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__ErpPermis__UserI__2FCF1A8A");
        });

        modelBuilder.Entity<FileManager>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FileMana__3214EC07238A5ACB");

            entity.ToTable("FileManager", "MEDIA");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Caption).HasMaxLength(1000);
            entity.Property(e => e.Url)
                .HasMaxLength(1000)
                .HasColumnName("URL");
        });

        modelBuilder.Entity<LaneAddress>(entity =>
        {
            entity.HasKey(e => e.AddressId).HasName("PK__LaneAddr__091C2AFB31AC8AF6");

            entity.ToTable("LaneAddresses", "HRM");

            entity.Property(e => e.AddressId).ValueGeneratedNever();
            entity.Property(e => e.AddressType).HasMaxLength(500);
            entity.Property(e => e.Area).HasMaxLength(2000);
            entity.Property(e => e.FamousPlace).HasMaxLength(2000);
            entity.Property(e => e.LaneAddressOne).HasMaxLength(2000);
            entity.Property(e => e.LaneAddressTwo).HasMaxLength(2000);

            entity.HasOne(d => d.City).WithMany(p => p.LaneAddresses)
                .HasForeignKey(d => d.CityId)
                .HasConstraintName("FK_LaneAddresses_Cities1");

            entity.HasOne(d => d.Person).WithMany(p => p.LaneAddresses)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_LaneAddresses_Persons");
        });

        modelBuilder.Entity<LinkedContentItem>(entity =>
        {
            entity.HasKey(e => e.LinkedItemId).HasName("PK__LinkedCo__6F9EA4BAEC8E4EB3");

            entity.ToTable("LinkedContentItems", "WEBCMS");

            entity.Property(e => e.LinkedItemId).ValueGeneratedNever();

            entity.HasOne(d => d.Content).WithMany(p => p.LinkedContentItemContents)
                .HasForeignKey(d => d.ContentId)
                .HasConstraintName("FK__LinkedCon__Conte__3B40CD36");

            entity.HasOne(d => d.LinkedContent).WithMany(p => p.LinkedContentItemLinkedContents)
                .HasForeignKey(d => d.LinkedContentId)
                .HasConstraintName("FK__LinkedCon__Linke__3C34F16F");
        });

        modelBuilder.Entity<LoginHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LoginHis__3214EC076E2D7173");

            entity.ToTable("LoginHistory", "HRM");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.LastLogin).HasColumnType("datetime");

            entity.HasOne(d => d.LoginUser).WithMany(p => p.LoginHistories)
                .HasForeignKey(d => d.LoginUserId)
                .HasConstraintName("FK_LoginHistory_LoginUsers");
        });

        modelBuilder.Entity<LoginUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LoginUse__3214EC07A80AD7A7");

            entity.ToTable("LoginUsers", "HRM");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Passwords).HasMaxLength(50);
            entity.Property(e => e.UserName).HasMaxLength(50);

            entity.HasOne(d => d.Person).WithMany(p => p.LoginUsers)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_LoginUsers_Persons");

            entity.HasOne(d => d.Settings).WithMany(p => p.LoginUsers)
                .HasForeignKey(d => d.SettingsId)
                .HasConstraintName("FK_LoginUsers_Settings");
        });

        modelBuilder.Entity<LoginUserDeviceDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LoginUse__3214EC07FACAF15D");

            entity.ToTable("LoginUserDeviceDetail", "HRM");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.DeviceIp)
                .HasMaxLength(100)
                .HasColumnName("DeviceIP");
            entity.Property(e => e.DeviceName).HasMaxLength(100);

            entity.HasOne(d => d.LoginUser).WithMany(p => p.LoginUserDeviceDetails)
                .HasForeignKey(d => d.LoginUserId)
                .HasConstraintName("FK_LoginUserDeviceDetail_LoginUsers");
        });

        modelBuilder.Entity<Material>(entity =>
        {
            entity.ToTable("Material", "INV");

            entity.Property(e => e.MaterialId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.MaterialName).HasMaxLength(500);
            entity.Property(e => e.MaterialSlug).HasMaxLength(500);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<Organization>(entity =>
        {
            entity.HasKey(e => e.OrganizationId).HasName("PK__Business__A1682FC590D5A421");

            entity.ToTable("Organizations", "Business");

            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.OrganizationName).HasMaxLength(500);
        });

        modelBuilder.Entity<Person>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Persons__3214EC07AA70B9B3");

            entity.ToTable("Persons", "HRM");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Cnic)
                .HasMaxLength(50)
                .HasColumnName("CNIC");
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(50);
            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.ImageUrl).HasColumnName("ImageURL");
            entity.Property(e => e.LastName).HasMaxLength(50);
            entity.Property(e => e.MobileNumber).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.SocialSecurity).HasMaxLength(10);

            entity.HasOne(d => d.Branc).WithMany(p => p.People)
                .HasForeignKey(d => d.BrancId)
                .HasConstraintName("FK_Persons_Branches");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("Products", "INV");

            entity.Property(e => e.ProductId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.ProductDescription).HasMaxLength(1000);
            entity.Property(e => e.ProductName).HasMaxLength(1000);
            entity.Property(e => e.ProductSlug).HasMaxLength(500);
            entity.Property(e => e.Qoh)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("QOH");
            entity.Property(e => e.Uomid).HasColumnName("UOMId");

            entity.HasOne(d => d.Brand).WithMany(p => p.Products)
                .HasForeignKey(d => d.BrandId)
                .HasConstraintName("FK_Products_Brands");

            entity.HasOne(d => d.Organization).WithMany(p => p.Products)
                .HasForeignKey(d => d.OrganizationId)
                .HasConstraintName("FK_Products_Organizations");

            entity.HasOne(d => d.SubCategory).WithMany(p => p.Products)
                .HasForeignKey(d => d.SubCategoryId)
                .HasConstraintName("FK_Products_SubCategoryId");

            entity.HasOne(d => d.Supplier).WithMany(p => p.Products)
                .HasForeignKey(d => d.SupplierId)
                .HasConstraintName("FK_Products_Supplier");

            entity.HasOne(d => d.Uom).WithMany(p => p.Products)
                .HasForeignKey(d => d.Uomid)
                .HasConstraintName("FK_Products_UOM");
        });

        modelBuilder.Entity<ProductBranch>(entity =>
        {
            entity.HasKey(e => e.ProductBranchesId);

            entity.ToTable("ProductBranches", "INV");

            entity.Property(e => e.ProductBranchesId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Branch).WithMany(p => p.ProductBranches)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("FK_ProductBranches_Branches");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductBranches)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_ProductBranches_Products");
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.ToTable("ProductImages", "INV");

            entity.Property(e => e.ProductImageId).ValueGeneratedNever();
            entity.Property(e => e.Caption).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasMaxLength(1000);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductImages)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_ProductImages_Products");
        });

        modelBuilder.Entity<ProductVariant>(entity =>
        {
            entity.HasKey(e => e.VariantId);

            entity.ToTable("ProductVariants", "INV");

            entity.Property(e => e.VariantId).ValueGeneratedNever();
            entity.Property(e => e.BarCode).HasMaxLength(500);
            entity.Property(e => e.Cost).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.LastPurchase).HasColumnType("datetime");
            entity.Property(e => e.LastSold).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.PromotionPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.QoH).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.QuantityPerUnit).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.RetailPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.SalesPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.SubUomid).HasColumnName("SubUOMId");

            entity.HasOne(d => d.Color).WithMany(p => p.ProductVariants)
                .HasForeignKey(d => d.ColorId)
                .HasConstraintName("FK_ProductVariants_Colors");

            entity.HasOne(d => d.Material).WithMany(p => p.ProductVariants)
                .HasForeignKey(d => d.MaterialId)
                .HasConstraintName("FK_ProductVariants_Material");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductVariants)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_ProductVariants_Products");

            entity.HasOne(d => d.Size).WithMany(p => p.ProductVariants)
                .HasForeignKey(d => d.SizeId)
                .HasConstraintName("FK_ProductVariants_Sizes");

            entity.HasOne(d => d.SubUom).WithMany(p => p.ProductVariants)
                .HasForeignKey(d => d.SubUomid)
                .HasConstraintName("FK_ProductVariants_UOMSub1");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__Reviews__74BC79CE25B83F27");

            entity.ToTable("Reviews", "WEBCMS");

            entity.Property(e => e.ReviewId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ReviewComment).HasMaxLength(1000);
            entity.Property(e => e.UserBrowser).HasMaxLength(50);
            entity.Property(e => e.UserIp)
                .HasMaxLength(50)
                .HasColumnName("UserIP");

            entity.HasOne(d => d.Content).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.ContentId)
                .HasConstraintName("FK__Reviews__Content__3D2915A8");

            entity.HasOne(d => d.LoginUser).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.LoginUserId)
                .HasConstraintName("FK__Reviews__LoginUs__3E1D39E1");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC070D90FCBC");

            entity.ToTable("Roles", "SYSTEM");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(50);
        });

        modelBuilder.Entity<Setting>(entity =>
        {
            entity.HasKey(e => e.SettingsId).HasName("PK__Settings__991B19FC2B30F11C");

            entity.ToTable("Settings", "SYSTEM");

            entity.Property(e => e.SettingsId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Size>(entity =>
        {
            entity.ToTable("Sizes", "INV");

            entity.Property(e => e.SizeId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.SizeName).HasMaxLength(1000);
            entity.Property(e => e.SizeSlug).HasMaxLength(100);
        });

        modelBuilder.Entity<StateProvince>(entity =>
        {
            entity.HasKey(e => e.StateProvinceId).HasName("PK__StatePro__9122A951A98A2E0D");

            entity.ToTable("StateProvince", "HRM");

            entity.Property(e => e.StateProvinceId).ValueGeneratedNever();
            entity.Property(e => e.StateProvinceName).HasMaxLength(1000);

            entity.HasOne(d => d.Country).WithMany(p => p.StateProvinces)
                .HasForeignKey(d => d.CountryId)
                .HasConstraintName("FK_StateProvince_Countries");
        });

        modelBuilder.Entity<SubCategory>(entity =>
        {
            entity.HasKey(e => e.SubCategoryId).HasName("PK_SubCategoryId");

            entity.ToTable("SubCategory", "INV");

            entity.Property(e => e.SubCategoryId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.SubCategoryName).HasMaxLength(1000);
            entity.Property(e => e.SubCategorySlug).HasMaxLength(500);

            entity.HasOne(d => d.Category).WithMany(p => p.SubCategories)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_SubCategoryId_Categories");
        });

        modelBuilder.Entity<Supplier>(entity =>
        {
            entity.HasKey(e => e.SupplierId).HasName("PK__Supplier__4BE666B48F48E7DA");

            entity.ToTable("Supplier", "HRM");

            entity.Property(e => e.SupplierId).ValueGeneratedNever();
            entity.Property(e => e.CompanyLogo).HasMaxLength(500);
            entity.Property(e => e.CreatedOn).HasColumnType("date");
            entity.Property(e => e.Ntn)
                .HasMaxLength(100)
                .HasColumnName("NTN");
            entity.Property(e => e.SupplierCode).HasMaxLength(500);

            entity.HasOne(d => d.Person).WithMany(p => p.Suppliers)
                .HasForeignKey(d => d.PersonId)
                .HasConstraintName("FK_Supplier_Persons");
        });

        modelBuilder.Entity<Uom>(entity =>
        {
            entity.ToTable("UOM", "INV");

            entity.Property(e => e.Uomid)
                .ValueGeneratedNever()
                .HasColumnName("UOMId");
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Uomname)
                .HasMaxLength(50)
                .HasColumnName("UOMName");
            entity.Property(e => e.Uomtype)
                .HasMaxLength(50)
                .HasColumnName("UOMType");
        });

        modelBuilder.Entity<Uomsub>(entity =>
        {
            entity.HasKey(e => e.SubUomid);

            entity.ToTable("UOMSub", "INV");

            entity.Property(e => e.SubUomid)
                .ValueGeneratedNever()
                .HasColumnName("SubUOMId");
            entity.Property(e => e.ConversionFactor).HasColumnType("decimal(4, 2)");
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.SubUomname)
                .HasMaxLength(500)
                .HasColumnName("SubUOMName");
            entity.Property(e => e.Uomid).HasColumnName("UOMId");

            entity.HasOne(d => d.Uom).WithMany(p => p.Uomsubs)
                .HasForeignKey(d => d.Uomid)
                .HasConstraintName("FK_UOMSub_UOM");
        });

        modelBuilder.Entity<UrlMenu>(entity =>
        {
            entity.HasKey(e => e.UrlMenuId).HasName("PK__UrlMenu__1E1429F7E962DFDF");

            entity.ToTable("UrlMenu", "SYSTEM");

            entity.Property(e => e.UrlMenuId).ValueGeneratedNever();
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.UrlMenuLink).HasMaxLength(50);
        });

        modelBuilder.Entity<UserAssignedBranch>(entity =>
        {
            entity.HasKey(e => e.UserAssignedBranches);

            entity.ToTable("UserAssignedBranches", "HRM");

            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Branch).WithMany(p => p.UserAssignedBranches)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("FK_UserAssignedBranches_Branches");

            entity.HasOne(d => d.LoginUser).WithMany(p => p.UserAssignedBranches)
                .HasForeignKey(d => d.LoginUserId)
                .HasConstraintName("FK_UserAssignedBranches_LoginUsers");
        });

        modelBuilder.Entity<Website>(entity =>
        {
            entity.HasKey(e => e.WebsiteId).HasName("PK__Website__3F146DA9D91D7C06");

            entity.ToTable("Website", "SYSTEM");

            entity.Property(e => e.WebsiteId).ValueGeneratedNever();
            entity.Property(e => e.SupportEmail).HasMaxLength(255);
            entity.Property(e => e.WebsiteName).HasMaxLength(500);
        });

        modelBuilder.Entity<WebsiteDatum>(entity =>
        {
            entity.HasKey(e => e.WebsiteDataId).HasName("PK__WebsiteD__E06C88F0BE7C6F72");

            entity.ToTable("WebsiteData", "SYSTEM");

            entity.Property(e => e.WebsiteDataId).ValueGeneratedNever();
            entity.Property(e => e.Title).HasMaxLength(50);
            entity.Property(e => e.Value)
                .HasMaxLength(50)
                .HasColumnName("value");

            entity.HasOne(d => d.Website).WithMany(p => p.WebsiteData)
                .HasForeignKey(d => d.WebsiteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__WebsiteDa__Websi__30C33EC3");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}