// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Amenity
{
    public int AmenityId { get; set; }

    public string AmenityName { get; set; }

    public string AmenityCategory { get; set; }

    public string IconClass { get; set; }

    public virtual ICollection<Reproperty> Properties { get; set; } = new List<Reproperty>();
}