// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class PropertyEnquiry
{
    public long EnquiryId { get; set; }

    public long PropertyId { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Message { get; set; }

    public byte EnquiryStatusTypeId { get; set; }

    public DateTime CreatedOn { get; set; }

    public virtual Reproperty Property { get; set; }
}