// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class PropertyPurposeType
{
    public byte PurposeTypeId { get; set; }

    public string PurposeTypeName { get; set; }

    public virtual ICollection<Reproperty> Reproperties { get; set; } = new List<Reproperty>();
}