// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class PropertySizeUnit
{
    public int PropertySizeUnitId { get; set; }

    public string UnitName { get; set; }

    public string UnitCode { get; set; }

    public decimal SqFtConversionFactor { get; set; }
}