// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class PropertyMedium
{
    public long PropertyMediaId { get; set; }

    public long PropertyId { get; set; }

    public byte MediaTypeId { get; set; }

    public string MediaUrl { get; set; }

    public string Caption { get; set; }

    public int DisplayOrder { get; set; }

    public bool IsFeatured { get; set; }

    public DateTime CreatedOn { get; set; }

    public virtual Reproperty Property { get; set; }
}