// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Readdress
{
    public int ReaddressId { get; set; }

    public string ReaddressName { get; set; }

    public int? CityId { get; set; }

    public string ReaddressType { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public int? RecompanyContactId { get; set; }

    public virtual City City { get; set; }

    public virtual RecompanyContact RecompanyContact { get; set; }
}