// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class RecompanyContact
{
    public int RecompanyContactId { get; set; }

    public string FullName { get; set; }

    public string Cnic { get; set; }

    public int? RecontactTypeId { get; set; }

    public int? RecompanyId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public string Email { get; set; }

    public string MobileHome { get; set; }

    public string MobileWork { get; set; }

    public string LandLine { get; set; }

    public virtual ICollection<Readdress> Readdresses { get; set; } = new List<Readdress>();

    public virtual Recompany Recompany { get; set; }

    public virtual RecontactType RecontactType { get; set; }
}