// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class RecontactType
{
    public int RecontactTypeId { get; set; }

    public string RecontactTypeName { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public virtual ICollection<RecompanyContact> RecompanyContacts { get; set; } = new List<RecompanyContact>();
}