// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class RelinksDatum
{
    public int RelinksDataId { get; set; }

    public string Title { get; set; }

    public int? LinkDataTypeId { get; set; }

    public string Description { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public bool? IsDeleted { get; set; }

    public int? Createdby { get; set; }

    public virtual ICollection<RelinksFile> RelinksFiles { get; set; } = new List<RelinksFile>();
}