// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class RelinksFile
{
    public int ReLinkFileId { get; set; }

    public string ReLinkFileCaption { get; set; }

    public int? ReLinkFileSortOrder { get; set; }

    public string ReLinkFileUrl { get; set; }

    public int? RelinkDataId { get; set; }

    public int? MediaTypeId { get; set; }

    public virtual RelinksDatum RelinkData { get; set; }
}