// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Reproperty
{
    public long PropertyId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string PropertyCode { get; set; }

    public int PropertyTypeId { get; set; }

    public byte PurposeTypeId { get; set; }

    public byte PropertyStatusTypeId { get; set; }

    public int CityId { get; set; }

    public int? LocalityId { get; set; }

    public int? SubLocalityId { get; set; }

    public string AddressDetails { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public decimal BaseSizeInSqFt { get; set; }

    public int DisplayUnitId { get; set; }

    public decimal? DimensionFront { get; set; }

    public decimal? DimensionDepth { get; set; }

    public decimal? CoveredAreaSqFt { get; set; }

    public decimal Price { get; set; }

    public decimal? SecurityDeposit { get; set; }

    public int? LeaseDurationMonths { get; set; }

    public int? AdvanceRentMonths { get; set; }

    public bool IsPriceNegotiable { get; set; }

    public decimal? MaintenanceFee { get; set; }

    public byte? Bedrooms { get; set; }

    public byte? Bathrooms { get; set; }

    public byte? FloorsCount { get; set; }

    public byte? ParkingSpaces { get; set; }

    public byte? ConstructionStatusTypeId { get; set; }

    public int? YearBuilt { get; set; }

    public string KhasraNumber { get; set; }

    public string KhewatNumber { get; set; }

    public string KhatoniNumber { get; set; }

    public string MouzaName { get; set; }

    public byte? WaterSourceTypeId { get; set; }

    public byte? NocStatusTypeId { get; set; }

    public byte? PossessionStatusTypeId { get; set; }

    public byte OwnershipTypeId { get; set; }

    public bool HasGas { get; set; }

    public bool HasElectricity { get; set; }

    public bool HasWaterSupply { get; set; }

    public bool HasSewerage { get; set; }

    public bool IsCornerPlot { get; set; }

    public bool IsMainBoulevard { get; set; }

    public bool IsParkFacing { get; set; }

    public bool IsFeatured { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public virtual City City { get; set; }

    public virtual Locality Locality { get; set; }

    public virtual ICollection<PropertyEnquiry> PropertyEnquiries { get; set; } = new List<PropertyEnquiry>();

    public virtual ICollection<PropertyMedium> PropertyMedia { get; set; } = new List<PropertyMedium>();

    public virtual RepropertyType PropertyType { get; set; }

    public virtual PropertyPurposeType PurposeType { get; set; }

    public virtual SubLocality SubLocality { get; set; }

    public virtual ICollection<Amenity> Amenities { get; set; } = new List<Amenity>();
}
