// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class RepropertyType
{
    public int PropertyTypeId { get; set; }

    public string PropertyTypeName { get; set; }

    public virtual ICollection<Reproperty> Reproperties { get; set; } = new List<Reproperty>();
}