// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Building
{
    public Guid BuildingId { get; set; }

    public string BuildingName { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? CreatedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public Guid? BranchId { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<Floor> Floors { get; set; } = new List<Floor>();
}