// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class Floor
{
    public Guid FloorId { get; set; }

    public string FloorName { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? CreatedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public Guid? BuildingId { get; set; }

    public virtual Building Building { get; set; }

    public virtual ICollection<ServingTable> ServingTables { get; set; } = new List<ServingTable>();
}