// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MainModels.Models;

public partial class ServingTable
{
    public Guid ServingTableId { get; set; }

    public string TableName { get; set; }

    public int? TableNumber { get; set; }

    public int? SittingCapacity { get; set; }

    public Guid? FloorId { get; set; }

    public virtual Floor Floor { get; set; }
}